#pragma once

// Dumped with TateDumper!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass ASACameraFunctionLibrary.ASACameraFunctionLibrary_C
class UASACameraFunctionLibrary_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UASACameraFunctionLibrary_C* GetDefaultObj();

	void FinalOverridePivotLocation(class APrimalCharacter* CameraOwnerCharacter, const struct FVector& CurrentPivotLocation, const struct FVector& DesiredPivotLocation, class UObject** __WorldContext);
	bool ShouldApplyAnyPitchBasedModifier(class APrimalCharacter* CameraOwnerCharacter, class UObject** __WorldContext, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool* K2Node_DynamicCast_bSuccess);
	double ApplyPitchBasedModifierToArmLengthInterp(class APrimalCharacter* CameraOwnerCharacter, const struct FPrimalCameraParams& CameraParams, TArray<struct FPrimalCameraPitchBasedModifier>* PitchBasedModifiers, class UObject** __WorldContext, double* PitchModifierAlpha, int32 FoundEntryIndex, int32* CallFunc_Array_Length_ReturnValue, bool CallFunc_ShouldApplyAnyPitchBasedModifier_bShouldApplyAnyModifier, bool* CallFunc_IsValid_ReturnValue, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldApplyModifier, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldLerp, double* CallFunc_ShouldApplyPitchBasedModifier_LerpAlpha, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item_1, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldApplyModifier_1, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldLerp_1, double* CallFunc_ShouldApplyPitchBasedModifier_LerpAlpha_1, bool* CallFunc_EqualEqual_DoubleDouble_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, double CallFunc_Lerp_ReturnValue, double CallFunc_Lerp_ReturnValue_1, double CallFunc_Lerp_ReturnValue_2, struct FPrimalCameraInterpParams* K2Node_MakeStruct_PrimalCameraInterpParams, double* CallFunc_Lerp_A_ImplicitCast, double* CallFunc_Lerp_A_ImplicitCast_1, double* CallFunc_Lerp_A_ImplicitCast_2, double CallFunc_SelectFloat_B_ImplicitCast, double CallFunc_Lerp_B_ImplicitCast, double CallFunc_Lerp_B_ImplicitCast_1, double CallFunc_Lerp_B_ImplicitCast_2, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float* K2Node_MakeStruct_TargetVelocity_ImplicitCast, float* K2Node_MakeStruct_SpringStiffness_ImplicitCast, float* K2Node_MakeStruct_CriticalDamping_ImplicitCast);
	void DebugPitchBasedModifier(class APrimalCharacter* CameraOwnerCharacter, struct FPrimalCameraPitchBasedModifier* PitchBasedModifier, int32 EntryIndex, double* ModifierAlpha, class UObject** __WorldContext, bool* CallFunc_IsValid_ReturnValue);
	void FinalOverridePivotOffset(class APrimalCharacter* CameraOwnerCharacter, const struct FPrimalCameraParams& CameraParams, TArray<struct FPrimalCameraPitchBasedModifier>* PitchBasedModifiers, const struct FVector& DesiredPivotOffset, class UObject** __WorldContext);
	double ApplyPitchBasedModifierToPivotOffset(class APrimalCharacter* CameraOwnerCharacter, const struct FPrimalCameraParams& CameraParams, TArray<struct FPrimalCameraPitchBasedModifier>* PitchBasedModifiers, const struct FVector& DesiredPivotOffset, class UObject** __WorldContext, double* PitchModifierAlpha, int32 FoundEntryIndex, int32* CallFunc_Array_Length_ReturnValue, const struct FVector& CallFunc_GetTPVCameraOffset_ReturnValue, bool* CallFunc_IsValid_ReturnValue, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item, const struct FVector& CallFunc_SelectVector_ReturnValue, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldApplyModifier, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldLerp, double* CallFunc_ShouldApplyPitchBasedModifier_LerpAlpha, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item_1, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldApplyModifier_1, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldLerp_1, double* CallFunc_ShouldApplyPitchBasedModifier_LerpAlpha_1, const struct FVector& CallFunc_SelectVector_ReturnValue_1, bool* CallFunc_EqualEqual_DoubleDouble_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, struct FVector* CallFunc_VLerp_ReturnValue, double CallFunc_SelectFloat_B_ImplicitCast, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float* CallFunc_VLerp_Alpha_ImplicitCast);
	double ApplyPitchBasedModifierToArmLength(class APrimalCharacter* CameraOwnerCharacter, const struct FPrimalCameraParams& CameraParams, TArray<struct FPrimalCameraPitchBasedModifier>* PitchBasedModifiers, double CurrentArmLength, double DesiredArmLength, class UObject** __WorldContext, double* PitchModifierAlpha, int32 FoundEntryIndex, int32* CallFunc_Array_Length_ReturnValue, bool CallFunc_ShouldApplyAnyPitchBasedModifier_bShouldApplyAnyModifier, bool* CallFunc_IsValid_ReturnValue, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item, bool* CallFunc_GreaterEqual_DoubleDouble_ReturnValue, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldApplyModifier, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldLerp, double* CallFunc_ShouldApplyPitchBasedModifier_LerpAlpha, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item_1, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldApplyModifier_1, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldLerp_1, double* CallFunc_ShouldApplyPitchBasedModifier_LerpAlpha_1, double* K2Node_VariableGet_DesiredArmLength_ImplicitCast, bool* CallFunc_EqualEqual_DoubleDouble_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, double CallFunc_Lerp_ReturnValue, double* CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast, float* K2Node_VariableSetRef_Target_ImplicitCast, double CallFunc_SelectFloat_B_ImplicitCast, double CallFunc_Lerp_B_ImplicitCast, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast);
	double ShouldApplyPitchBasedModifier(class APrimalCharacter* CameraOwnerCharacter, struct FPrimalCameraPitchBasedModifier* PitchBasedModifier, class UObject** __WorldContext, double* LerpAlpha, bool* CallFunc_IsValid_ReturnValue, double CallFunc_BreakVector2D_X, double CallFunc_BreakVector2D_Y, double CallFunc_BreakVector2D_X_1, double CallFunc_BreakVector2D_Y_1, double CallFunc_FMax_ReturnValue, double CallFunc_FMax_ReturnValue_1, const struct FRotator& CallFunc_GetPrimalCameraDesiredPivotRotation_ReturnValue, float* CallFunc_BreakRotator_Roll, float* CallFunc_BreakRotator_Pitch, float* CallFunc_BreakRotator_Yaw, bool CallFunc_InRange_FloatFloat_ReturnValue, double* CallFunc_MapRangeClamped_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_InRange_FloatFloat_ReturnValue_1, double CallFunc_InRange_FloatFloat_Value_ImplicitCast, double CallFunc_InRange_FloatFloat_Value_ImplicitCast_1);
	double ApplyPitchBasedModifierToInterpParams(class APrimalCharacter* CameraOwnerCharacter, const struct FPrimalCameraParams& CameraParams, struct FPrimalCameraInterpParams* InterpParamsX, struct FPrimalCameraInterpParams* InterpParamsY, struct FPrimalCameraInterpParams* InterpParamsZ, TArray<struct FPrimalCameraPitchBasedModifier>* PitchBasedModifiers, class UObject** __WorldContext, double* PitchModifierAlpha, const struct FPrimalCameraInterpParams& FinalInterpParams, struct FPrimalCameraInterpParams* InterpParamsToModify, int32 FoundEntryIndex, int32* CallFunc_Array_Length_ReturnValue, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool* CallFunc_IsValid_ReturnValue, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item_1, bool CallFunc_Array_IsValidIndex_ReturnValue, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldApplyModifier, bool* CallFunc_ShouldApplyPitchBasedModifier_bShouldLerp, double* CallFunc_ShouldApplyPitchBasedModifier_LerpAlpha, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue_1, struct FPrimalCameraPitchBasedModifier* CallFunc_Array_Get_Item_2, bool CallFunc_BooleanAND_ReturnValue_1, bool* CallFunc_EqualEqual_DoubleDouble_ReturnValue, double CallFunc_Lerp_ReturnValue, double CallFunc_Lerp_ReturnValue_1, double CallFunc_Lerp_ReturnValue_2, struct FPrimalCameraInterpParams* K2Node_MakeStruct_PrimalCameraInterpParams, double* CallFunc_Lerp_A_ImplicitCast, double* CallFunc_Lerp_A_ImplicitCast_1, double* CallFunc_Lerp_A_ImplicitCast_2, double CallFunc_SelectFloat_B_ImplicitCast, double CallFunc_Lerp_B_ImplicitCast, double CallFunc_Lerp_B_ImplicitCast_1, double CallFunc_Lerp_B_ImplicitCast_2, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float* K2Node_MakeStruct_SpringStiffness_ImplicitCast, float* K2Node_MakeStruct_TargetVelocity_ImplicitCast, float* K2Node_MakeStruct_CriticalDamping_ImplicitCast);
	struct FPrimalCameraInterpParams FinalOverrideCameraArmLengthInterpParams(class APrimalCharacter* CameraOwnerCharacter, const struct FPrimalCameraParams& CameraParams, class UObject** __WorldContext);
	struct FVector FinalOverrideCameraArmLength(class APrimalCharacter* CharacterToKeepOnScreen, const struct FPrimalCameraParams& CameraParams, class APrimalCharacter* CameraOwnerCharacter, class UObject** __WorldContext, double CharacterScreenAreaY, double CharacterScreenAreaX);
	double Final_Override_Pivot_Interp_Params(class APrimalCharacter* CameraOwnerCharacter, const struct FPrimalCameraParams& CameraParams, struct FPrimalCameraInterpParams* LastPivotInterpParamsX, struct FPrimalCameraInterpParams* LastPivotInterpParamsY, struct FPrimalCameraInterpParams* LastPivotInterpParamsZ, class UObject** __WorldContext, double CharScreenAreaY, double CharScreenAreaX, int32 EntryIndexForLerping, double* LerpAlpha, bool* CallFunc_IsValid_ReturnValue, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool* K2Node_DynamicCast_bSuccess, bool CallFunc_IsTimeSince_ReturnValue, bool CallFunc_IsTimeSince_ReturnValue_1, bool CallFunc_IsProneOrSitting_ReturnValue, bool CallFunc_IsTimeSince_ReturnValue_2, bool CallFunc_IsCrouching_ReturnValue, bool* CallFunc_ShouldUseLongFallCameraPivotZValues_ReturnValue, bool* CallFunc_IsValid_ReturnValue_1, double CallFunc_GetWorldDeltaSeconds_ReturnValue, struct FPrimalCameraInterpParams* K2Node_MakeStruct_PrimalCameraInterpParams, double* CallFunc_Less_DoubleDouble_A_ImplicitCast, float* K2Node_MakeStruct_TargetVelocity_ImplicitCast, float* K2Node_MakeStruct_CriticalDamping_ImplicitCast, float* K2Node_MakeStruct_SpringStiffness_ImplicitCast);
	double ApplyModifiersToInterpParams(class APrimalCharacter* CameraOwnerCharacter, const struct FPrimalCameraParams& CameraParams, const struct FPrimalCameraInterpParams& InterpParams, TArray<struct FPrimalCameraInterpScreenAreaModifier>* InterpParamsModifiers, class FName DebugScreenModifierId, class UObject** __WorldContext, double CharScreenAreaY, double CharScreenAreaX, int32 EntryIndexForLerping, double* LerpAlpha, int32* CallFunc_Array_Length_ReturnValue, bool* CallFunc_IsValid_ReturnValue, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool* K2Node_DynamicCast_bSuccess, bool* CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsCrouching_ReturnValue, bool CallFunc_IsProneOrSitting_ReturnValue, bool CallFunc_IsTimeSince_ReturnValue, bool CallFunc_IsTimeSince_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, struct FPrimalCameraInterpScreenAreaModifier* CallFunc_Array_Get_Item, double CallFunc_BreakVector2D_X, double CallFunc_BreakVector2D_Y, double CallFunc_FMax_ReturnValue, double CallFunc_BreakVector2D_X_1, double CallFunc_BreakVector2D_Y_1, double CallFunc_FMax_ReturnValue_1, double* CallFunc_MapRangeClamped_ReturnValue, bool CallFunc_InRange_FloatFloat_ReturnValue, bool CallFunc_InRange_FloatFloat_ReturnValue_1, double* CallFunc_WorldLocationToScreenArea_ScreenAreaX, double* CallFunc_WorldLocationToScreenArea_ScreenAreaY, double CallFunc_WorldLocationToScreenArea_ViewportSizeX, double CallFunc_WorldLocationToScreenArea_ViewportSizeY, double* CallFunc_WorldLocationToScreenArea_ScreenRawPosX, double* CallFunc_WorldLocationToScreenArea_ScreenRawPosY, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool Temp_bool_Variable, bool CallFunc_Array_IsValidIndex_ReturnValue, struct FPrimalCameraInterpParams* K2Node_Select_Default, bool* CallFunc_EqualEqual_DoubleDouble_ReturnValue, double CallFunc_Lerp_ReturnValue, double CallFunc_Lerp_ReturnValue_1, double CallFunc_Lerp_ReturnValue_2, struct FPrimalCameraInterpParams* K2Node_MakeStruct_PrimalCameraInterpParams, double CallFunc_SelectFloat_B_ImplicitCast, double CallFunc_Lerp_B_ImplicitCast, double CallFunc_Lerp_B_ImplicitCast_1, double CallFunc_Lerp_B_ImplicitCast_2, double* CallFunc_Lerp_A_ImplicitCast, double* CallFunc_Lerp_A_ImplicitCast_1, double* CallFunc_Lerp_A_ImplicitCast_2, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float* K2Node_MakeStruct_SpringStiffness_ImplicitCast, float* K2Node_MakeStruct_TargetVelocity_ImplicitCast, float* K2Node_MakeStruct_CriticalDamping_ImplicitCast);
	double WorldLocationToScreenArea(class APrimalCharacter* CameraOwnerCharacter, class UObject** __WorldContext, bool* CallFunc_IsValid_ReturnValue, class AController** CallFunc_GetController_ReturnValue, const struct FVector2D& CallFunc_ProjectWorldToScreen_ScreenPosition, bool CallFunc_ProjectWorldToScreen_ReturnValue, const struct FGeometry& CallFunc_GetPlayerScreenWidgetGeometry_ReturnValue, double CallFunc_BreakVector2D_X, double CallFunc_BreakVector2D_Y, const struct FVector2D& CallFunc_GetAbsoluteSize_ReturnValue, bool* CallFunc_IsValid_ReturnValue_1, double CallFunc_BreakVector2D_X_1, double CallFunc_BreakVector2D_Y_1, bool* CallFunc_EqualEqual_DoubleDouble_ReturnValue, bool* CallFunc_EqualEqual_DoubleDouble_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast_1);
};

}


