#pragma once

// Dumped with TateDumper!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass ASACameraFunctionLibrary.ASACameraFunctionLibrary_C
class UASACameraFunctionLibrary_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UASACameraFunctionLibrary_C* GetDefaultObj();

	struct FVector FinalOverridePivotLocation(struct FVector* CurrentPivotLocation, class UObject** __WorldContext);
	bool ShouldApplyAnyPitchBasedModifier(class UObject** __WorldContext);
	double ApplyPitchBasedModifierToArmLengthInterp(class UObject** __WorldContext, double PitchModifierAlpha, int32* CallFunc_Array_Length_ReturnValue, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item_1, bool CallFunc_BooleanAND_ReturnValue_1, double* CallFunc_SelectFloat_ReturnValue, double CallFunc_MultiplyMultiply_FloatFloat_ReturnValue, double* CallFunc_Divide_DoubleFloat_ReturnValue, const struct FPrimalCameraInterpParams& K2Node_MakeStruct_PrimalCameraInterpParams, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float K2Node_MakeStruct_TargetVelocity_ImplicitCast, float K2Node_MakeStruct_SpringStiffness_ImplicitCast, float K2Node_MakeStruct_CriticalDamping_ImplicitCast);
	bool DebugPitchBasedModifier(const struct FPrimalCameraPitchBasedModifier& PitchBasedModifier, int32 EntryIndex, double ModifierAlpha, class UObject** __WorldContext);
	struct FVector FinalOverridePivotOffset(class UObject** __WorldContext);
	float ApplyPitchBasedModifierToPivotOffset(class UObject** __WorldContext, double PitchModifierAlpha, int32* CallFunc_Array_Length_ReturnValue, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item, struct FVector* CallFunc_SelectVector_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item_1, struct FVector* CallFunc_SelectVector_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_1, double* CallFunc_SelectFloat_ReturnValue, double CallFunc_MultiplyMultiply_FloatFloat_ReturnValue, double* CallFunc_Divide_DoubleFloat_ReturnValue, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast);
	double ApplyPitchBasedModifierToArmLength(class UObject** __WorldContext, double PitchModifierAlpha, int32* CallFunc_Array_Length_ReturnValue, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item_1, double K2Node_VariableGet_DesiredArmLength_ImplicitCast, double* CallFunc_SelectFloat_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, double* CallFunc_SelectFloat_ReturnValue_1, double CallFunc_MultiplyMultiply_FloatFloat_ReturnValue, double* CallFunc_Divide_DoubleFloat_ReturnValue, float K2Node_VariableSetRef_Target_ImplicitCast, double* CallFunc_SelectFloat_A_ImplicitCast, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast);
	double ShouldApplyPitchBasedModifier(const struct FPrimalCameraPitchBasedModifier& PitchBasedModifier, class UObject** __WorldContext, double LerpAlpha, double CallFunc_FMin_ReturnValue, double CallFunc_FMin_ReturnValue_1, float* CallFunc_BreakRotator_Roll, float* CallFunc_BreakRotator_Pitch, float* CallFunc_BreakRotator_Yaw, bool CallFunc_BooleanAND_ReturnValue, double CallFunc_MapRangeClamped_Value_ImplicitCast);
	double ApplyPitchBasedModifierToInterpParams(class UObject** __WorldContext, double PitchModifierAlpha, int32* CallFunc_Array_Length_ReturnValue, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item_1, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FPrimalCameraPitchBasedModifier& CallFunc_Array_Get_Item_2, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_4, bool CallFunc_EqualEqual_ByteByte_ReturnValue_5, double* CallFunc_SelectFloat_ReturnValue, double CallFunc_MultiplyMultiply_FloatFloat_ReturnValue, double* CallFunc_Divide_DoubleFloat_ReturnValue, const struct FPrimalCameraInterpParams& K2Node_MakeStruct_PrimalCameraInterpParams, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float K2Node_MakeStruct_SpringStiffness_ImplicitCast, float K2Node_MakeStruct_TargetVelocity_ImplicitCast, float K2Node_MakeStruct_CriticalDamping_ImplicitCast);
	struct FPrimalCameraParams FinalOverrideCameraArmLengthInterpParams(const struct FPrimalCameraInterpParams& OutInterpParams, class UObject** __WorldContext);
	double FinalOverrideCameraArmLength(double CurrentCameraArmLength, double DesiredCameraArmLength, class UObject** __WorldContext, double ScreenAreaToUse, bool* VelocityIsNearlyZero, struct FVector* WorldLocationToProject);
	double Final_Override_Pivot_Interp_Params(const struct FPrimalCameraPivotZInterpOverrides& PivotZInterpOverrides, const struct FPrimalCameraInterpParams& LastPivotInterpParamsX, const struct FPrimalCameraInterpParams& LastPivotInterpParamsY, const struct FPrimalCameraInterpParams& LastPivotInterpParamsZ, const struct FPrimalCameraInterpParams& PivotInterpParamsX, const struct FPrimalCameraInterpParams& PivotInterpParamsY, const struct FPrimalCameraInterpParams& PivotInterpParamsZ, class UObject** __WorldContext, double PrintModifierAlpha, double* TheScreenArea, double LerpAlpha, bool CallFunc_Less_DoubleDouble_ReturnValue, bool* CallFunc_BooleanOR_ReturnValue, const struct FPrimalCameraInterpParams& K2Node_MakeStruct_PrimalCameraInterpParams, double CallFunc_FInterpTo_Current_ImplicitCast, double CallFunc_Less_DoubleDouble_A_ImplicitCast, double CallFunc_FInterpTo_Current_ImplicitCast_1, double CallFunc_FInterpTo_Current_ImplicitCast_2, float K2Node_MakeStruct_TargetVelocity_ImplicitCast, float K2Node_MakeStruct_CriticalDamping_ImplicitCast, float K2Node_MakeStruct_SpringStiffness_ImplicitCast);
	double ApplyModifiersToInterpParams(class UObject** __WorldContext, struct FPrimalCameraInterpScreenAreaModifier* ScreenModifierForDebug, double PrintModifierAlpha, double* TheScreenArea, double LerpAlpha, int32* CallFunc_Array_Length_ReturnValue, bool* CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FPrimalCameraInterpScreenAreaModifier& CallFunc_Array_Get_Item, double CallFunc_FMin_ReturnValue, double CallFunc_FMin_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool Temp_bool_Variable, const struct FPrimalCameraInterpParams& K2Node_Select_Default, double* CallFunc_SelectFloat_ReturnValue, double CallFunc_MultiplyMultiply_FloatFloat_ReturnValue, double* CallFunc_Divide_DoubleFloat_ReturnValue, const struct FPrimalCameraInterpParams& K2Node_MakeStruct_PrimalCameraInterpParams, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float K2Node_MakeStruct_SpringStiffness_ImplicitCast, float K2Node_MakeStruct_TargetVelocity_ImplicitCast, float K2Node_MakeStruct_CriticalDamping_ImplicitCast);
	bool WorldLocationToScreenArea(struct FVector* WorldLocationToProject, class UObject** __WorldContext, double* ScreenAreaX, double* ScreenAreaY, double* ViewportSizeX, double* ViewportSizeY, double* ScreenRawPosX, double* ScreenRawPosY, class AController** CallFunc_GetController_ReturnValue, class APlayerController** CallFunc_CastToPlayerController_ReturnValue, double* CallFunc_Divide_DoubleFloat_ReturnValue, double* CallFunc_Divide_DoubleFloat_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast, float* CallFunc_Divide_DoubleFloat_B_ImplicitCast_1);
};

}


