#pragma once

// Dumped with TateDumper!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass BPFL_GlobalFunctions.BPFL_GlobalFunctions_C
class UBPFL_GlobalFunctions_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UBPFL_GlobalFunctions_C* GetDefaultObj();

	double GetIsModPaidStatus(const struct FInstallProgressMod& ModInfo, bool* ForcePaid, bool* ForcePurchased, class UObject** __WorldContext, bool* Paid, bool* Purchased);
	class UUI_ModPage_C* CreateModPageFromStandalone(int64 Mod_ID, int32* DrawUIOnZOrder, class UUI_GameSlot_C** UI_GameSlotRef, class UObject** __WorldContext);
	bool GetIsModValid(const struct FInstallProgressMod& ModInfo, class UObject** __WorldContext);
	class FString DebugMod(const struct FInstallProgressMod& InstallProgressMod, bool Debug_BroadcastEvent, bool DebugInstallingUpdating, class UObject** __WorldContext, const struct FInstallProgressMod& DebugingMod, class FString* TotalPrint, enum class EGameModsEvent* CalledEvent, class UObject** Owner, enum class EInstallStatus Temp_byte_Variable, int32 CallFunc_ReplaceInline_ReturnValue, enum class EInstallStatus Temp_byte_Variable_1, const class FString& CallFunc_GetModName_Name, class FString* K2Node_Select_Default, class FString* K2Node_Select_Default_1, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, const class FString& CallFunc_Conv_IntToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, const class FString& CallFunc_Concat_StrStr_ReturnValue_4, const class FString& CallFunc_Concat_StrStr_ReturnValue_5, class FText* CallFunc_Conv_Int64ToText_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue, class FText* CallFunc_Conv_Int64ToText_ReturnValue_1, class FText* CallFunc_Conv_Int64ToText_ReturnValue_2, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, const class FString& CallFunc_Conv_TextToString_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_6, const class FString& CallFunc_Concat_StrStr_ReturnValue_7, const class FString& CallFunc_Concat_StrStr_ReturnValue_8, const class FString& CallFunc_Concat_StrStr_ReturnValue_9, const class FString& CallFunc_Concat_StrStr_ReturnValue_10, const class FString& CallFunc_Concat_StrStr_ReturnValue_11, const class FString& CallFunc_Concat_StrStr_ReturnValue_12, const class FString& CallFunc_Concat_StrStr_ReturnValue_13, const class FString& CallFunc_Concat_StrStr_ReturnValue_14, const class FString& CallFunc_Concat_StrStr_ReturnValue_15, const class FString& CallFunc_Concat_StrStr_ReturnValue_16, const class FString& CallFunc_Concat_StrStr_ReturnValue_17, const class FString& CallFunc_Concat_StrStr_ReturnValue_18, const class FString& CallFunc_Concat_StrStr_ReturnValue_19, const class FString& CallFunc_Concat_StrStr_ReturnValue_20, const class FString& CallFunc_Concat_StrStr_ReturnValue_21, const class FString& CallFunc_Concat_StrStr_ReturnValue_22);
	int64 Is_There_Enough_Space_to_Install_Mod(int64 DiskSpace, struct FInstallProgressMod* ModToInstall, class UObject** __WorldContext, bool* EnoughSpace, bool CallFunc_GreaterEqual_Int64Int64_ReturnValue);
	double GetProcessedBarProgress(int32* Amount, enum class ELibraryProgressState* InstallProgressState, class UObject** __WorldContext, bool MaintainPreviousValue, double Temp_real_Variable, double Temp_real_Variable_1, double* CallFunc_MapRangeClamped_ReturnValue, double* CallFunc_MapRangeClamped_ReturnValue_1, double Temp_real_Variable_2, double Temp_real_Variable_3, double Temp_real_Variable_4, double Temp_real_Variable_5, double Temp_real_Variable_6, double Temp_real_Variable_7, double Temp_real_Variable_8, double Temp_real_Variable_9, double Temp_real_Variable_10, enum class ELibraryProgressState Temp_byte_Variable, double* K2Node_Select_Default, double CallFunc_Divide_DoubleDouble_ReturnValue);
	void GetIsModAvailable(const struct FInstallProgressMod& ModInfo, class UObject** __WorldContext, bool* Is_Available);
	class UUI_ModPage_C* CreateModPageFromID(int64 Mod_ID, int32* DrawUIOnZOrder, class UObject** __WorldContext);
	class UUI_ModPage_C* CreateModPageFromStoreMenu(int64 Mod_ID, int32* DrawUIOnZOrder, class UUI_GameSlot_C** UI_GameSlotRef, class UUI_StoreMenu_C** UI_StoreMenu, class UObject** __WorldContext);
	bool FormatDownloadNumber(int64 Value, class UObject** __WorldContext, class FText* FinalAmount, class FText* CallFunc_Conv_Int64ToText_ReturnValue, int64* CallFunc_Divide_Int64Int64_ReturnValue, class FText* CallFunc_Conv_Int64ToText_ReturnValue_1, int64* CallFunc_Divide_Int64Int64_ReturnValue_1, const class FString& CallFunc_Conv_TextToString_ReturnValue, class FText* CallFunc_Conv_Int64ToText_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, const class FString& CallFunc_GetSubstring_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, class FText CallFunc_Conv_StringToText_ReturnValue_1, int64* CallFunc_Divide_Int64Int64_ReturnValue_2, int64* CallFunc_Divide_Int64Int64_ReturnValue_3, class FText* CallFunc_Conv_Int64ToText_ReturnValue_3, class FText* CallFunc_Conv_Int64ToText_ReturnValue_4, const class FString& CallFunc_Conv_TextToString_ReturnValue_2, const class FString& CallFunc_Conv_TextToString_ReturnValue_3, const class FString& CallFunc_Concat_StrStr_ReturnValue_4, const class FString& CallFunc_GetSubstring_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue_5, const class FString& CallFunc_Concat_StrStr_ReturnValue_6, class FText CallFunc_Conv_StringToText_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_7, class FText CallFunc_Conv_StringToText_ReturnValue_3, bool CallFunc_Less_Int64Int64_ReturnValue, bool CallFunc_Less_Int64Int64_ReturnValue_1);
	bool GetModVersion(const struct FInstallProgressMod& ModInfo, class UObject** __WorldContext, class FText* FinalAmount, TArray<class FString>* NameLikeChar, class FString* ModsFileName, int32 CallFunc_Add_IntInt_ReturnValue, int32* CallFunc_Array_Length_ReturnValue, int32* CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, struct FFile* CallFunc_Array_Get_Item, class FString* CallFunc_Array_Get_Item_1, bool CallFunc_IsNumeric_ReturnValue, bool* CallFunc_EqualEqual_Int64Int64_ReturnValue, int32* CallFunc_Array_Length_ReturnValue_2, class FText CallFunc_Conv_StringToText_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, bool Temp_bool_Variable, class FText* K2Node_Select_Default, class FString* CallFunc_Array_Get_Item_2, int32 CallFunc_ReplaceInline_ReturnValue, int32* CallFunc_Array_Length_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, int32* CallFunc_Len_ReturnValue, int32* CallFunc_FindSubstring_ReturnValue, const class FString& CallFunc_GetSubstring_ReturnValue);
	void GetDownloadCount(const struct FInstallProgressMod& ModInfo, class UObject** __WorldContext, class FText* FinalAmount, class FText CallFunc_FormatDownloadNumber_FinalAmount);
	void GetModName(const struct FInstallProgressMod& ModInfo, class UObject** __WorldContext, class FString* Name);
	bool GetModSize(const struct FInstallProgressMod& ModInfo, class UObject** __WorldContext, struct FCFCoreFileSize* SizeStruct, class FText* SizeInText, int64 Bytes, struct FFile* CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue, const class FString& CallFunc_FormatFileSize_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, struct FCFCoreFileSize* CallFunc_BreakFileSize_ReturnValue, bool* CallFunc_EqualEqual_Int64Int64_ReturnValue, int32* CallFunc_Array_Length_ReturnValue);
	bool GetAuthorName(const struct FInstallProgressMod& ModInfo, class UObject** __WorldContext, class FString* Local_TotalAuthors, struct FModAuthor* CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue, int32* CallFunc_Array_Length_ReturnValue, const class FString& CallFunc_StringLimit_NewString, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1);
	struct FSlateColor CreateButtonStyleFromSingleColor(struct FLinearColor* Color, class UObject** __WorldContext, struct FButtonStyle* ButtonStyle, struct FLinearColor* CallFunc_Add_LinearColorLinearColor_ReturnValue, const struct FSlateBrush& K2Node_MakeStruct_SlateBrush, const struct FSlateBrush& K2Node_MakeStruct_SlateBrush_1, const struct FLinearColor& CallFunc_Multiply_LinearColorFloat_ReturnValue, const struct FLinearColor& CallFunc_Multiply_LinearColorFloat_ReturnValue_1, const struct FSlateBrush& K2Node_MakeStruct_SlateBrush_2, const struct FSlateBrush& K2Node_MakeStruct_SlateBrush_3, const struct FButtonStyle& K2Node_MakeStruct_ButtonStyle);
	int32 HEXtoByte(class FString* First_value, class FString* Second_value, class UObject** __WorldContext, uint8* InputPin1, TArray<class FString>* HexDigits, int32 CallFunc_Array_Find_ReturnValue, int32 CallFunc_Array_Find_ReturnValue_1, int32* CallFunc_And_IntInt_ReturnValue, int32* CallFunc_And_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, uint8 CallFunc_Conv_IntToByte_ReturnValue);
	TArray<class FString> HEXtoSRGB(const class FString& String, class UObject** __WorldContext, struct FColor* Color, class FString* CallFunc_Array_Get_Item, class FString* CallFunc_Array_Get_Item_1, class FString* CallFunc_Array_Get_Item_2, class FString* CallFunc_Array_Get_Item_3, uint8 CallFunc_HEXtoByte_InputPin1, class FString* CallFunc_Array_Get_Item_4, class FString* CallFunc_Array_Get_Item_5, uint8 CallFunc_HEXtoByte_InputPin1_1, class FString* CallFunc_Array_Get_Item_6, class FString* CallFunc_Array_Get_Item_7, uint8 CallFunc_HEXtoByte_InputPin1_2, uint8 CallFunc_HEXtoByte_InputPin1_3, struct FColor* K2Node_MakeStruct_Color);
	bool SRGBtoHEX(struct FColor* Color, class UObject** __WorldContext, const TArray<class FString>& String, uint8* CallFunc_Array_Get_Item, int32* CallFunc_Array_Length_ReturnValue, const class FString& CallFunc_ByteToHex_ReturnValue, const class FString& CallFunc_JoinStringArray_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32* CallFunc_Array_Add_ReturnValue);
	int32 ByteToHex(uint8* InputPin, class UObject** __WorldContext, TArray<class FString>* HexDigits, int32* CallFunc_And_IntInt_ReturnValue, int32* CallFunc_And_IntInt_ReturnValue_1, class FString* CallFunc_Array_Get_Item, class FString* CallFunc_Array_Get_Item_1, const class FString& CallFunc_Concat_StrStr_ReturnValue);
	class UWidget* SetFocusedWidget(class UObject** __WorldContext, TArray<class UUI_StoreMenu_C*>* CallFunc_GetAllWidgetsOfClass_FoundWidgets, class UUI_StoreMenu_C** CallFunc_Array_Get_Item, bool* CallFunc_IsValid_ReturnValue);
	bool TextLimit(const class FString& String, class UObject** __WorldContext, const class FString& CallFunc_StringLimit_NewString, class FText CallFunc_Conv_StringToText_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue_1, int32* CallFunc_Array_Length_ReturnValue);
	void CheckPlayerInputDevices(class UObject** __WorldContext, enum class ENUM_InputDevices* UsingGamepad_, bool Temp_bool_Variable, TArray<class UUI_StoreMenu_C*>* CallFunc_GetAllWidgetsOfClass_FoundWidgets, enum class ENUM_InputDevices Temp_byte_Variable, class UUI_StoreMenu_C** CallFunc_Array_Get_Item, bool* CallFunc_IsValid_ReturnValue, enum class ENUM_InputDevices Temp_byte_Variable_1, enum class ENUM_InputDevices* K2Node_Select_Default);
	bool StringLimit(const class FString& String, class UObject** __WorldContext, class FString* NewString, class FString* LocalString, int32* CallFunc_Int32_AddOne_ReturnValue, class FString* CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue, int32* CallFunc_Array_Length_ReturnValue, int32* CallFunc_Array_Length_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1);
	void ErrorMessage(class UObject** Object, const class FString& ErrorMessage, class UObject** __WorldContext);
};

}


