#pragma once

// Dumped with TateDumper!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x431 (0xEA9 - 0xA78)
// WidgetBlueprintGeneratedClass CheatMenu.CheatMenu_C
class UCheatMenu_C : public UUI_DebugSpawnMenu
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xA78(0x8)(BlueprintVisible, ExportObject, EditFixedSize, DisableEditOnInstance, SubobjectReference)
	class UCheckBox*                             BabyCheck;                                         // 0xA80(0x8)(Edit, BlueprintReadOnly, Net, EditFixedSize, Parm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             BlueprintCheckBox;                                 // 0xA88(0x8)(Edit, BlueprintVisible, ExportObject, EditFixedSize, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UCanvasPanel*                          CharacterPresetOptions;                            // 0xA90(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UCanvasPanel*                          CheatOptions;                                      // 0xA98(0x8)(ConstParm, BlueprintVisible, Net, Parm, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UEditableTextBox*                      CheatStringAddition;                               // 0xAA0(0x8)(ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UButton*                               ClearFilterButton;                                 // 0xAA8(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, OutParm, ReturnParm, Config, EditConst, SubobjectReference)
	class UButton*                               CloseButton;                                       // 0xAB0(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, EditFixedSize, OutParm, ReturnParm, Config, GlobalConfig, InstancedReference, SubobjectReference)
	class UCheckBox*                             DebugTouchCheck;                                   // 0xAB8(0x8)(Edit, ConstParm, ExportObject, EditFixedSize, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UCanvasPanel*                          DebugView;                                         // 0xAC0(0x8)(ConstParm, BlueprintReadOnly, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	class UDataListPanel*                        DinoList;                                          // 0xAC8(0x8)(Edit, ConstParm, BlueprintVisible, Net, EditFixedSize, Parm, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UCanvasPanel*                          DinoOptions;                                       // 0xAD0(0x8)(ConstParm, ExportObject, BlueprintReadOnly, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	class UEditableTextBox*                      DinoSpawnLevelBox;                                 // 0xAD8(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, OutParm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCanvasPanel*                          EggOptions;                                        // 0xAE0(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, ZeroConstructor, Config, EditConst, SubobjectReference)
	class UCheckBox*                             EngramCheckBox;                                    // 0xAE8(0x8)(ConstParm, BlueprintVisible, EditFixedSize, Parm, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             FemaleCheck;                                       // 0xAF0(0x8)(Edit, EditFixedSize, OutParm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             FertilizedCheckBox;                                // 0xAF8(0x8)(ExportObject, EditFixedSize, Parm, OutParm, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UCanvasPanel*                          FilterPanel;                                       // 0xB00(0x8)(Edit, ConstParm, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UImage*                                Image;                                             // 0xB08(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Config, DisableEditOnInstance)
	class UImage*                                Image_4;                                           // 0xB10(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Config, DisableEditOnInstance, RepNotify, NonTransactional)
	class UImage*                                Image_48;                                          // 0xB18(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Config, DisableEditOnInstance, RepNotify, NoDestructor)
	class UImage*                                Image_97;                                          // 0xB20(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Config, DisableEditOnInstance, Interp, AutoWeak)
	class UCheckBox*                             IncludeItemsCheck;                                 // 0xB28(0x8)(ConstParm, ExportObject, BlueprintReadOnly, Net, OutParm, Transient, EditConst, SubobjectReference)
	class UCanvasPanel*                          ItemOptions;                                       // 0xB30(0x8)(Edit, ExportObject, Net, OutParm, ZeroConstructor, ReturnParm, Config, EditConst, SubobjectReference)
	class UCheckBox*                             MaleCheck;                                         // 0xB38(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, EditFixedSize, OutParm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UEditableTextBox*                      NamesFilterInputField;                             // 0xB40(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Parm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UEditableTextBox*                      NumberEggsToSpawn;                                 // 0xB48(0x8)(ConstParm, BlueprintReadOnly, EditFixedSize, Parm, OutParm, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UEditableTextBox*                      NumToSpawnTextBox;                                 // 0xB50(0x8)(ExportObject, Net, EditFixedSize, Parm, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UEditableTextBox*                      QualityToSpawnTextBox;                             // 0xB58(0x8)(ConstParm, BlueprintReadOnly, Net, EditFixedSize, Parm, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UTextBlock*                            ReferenceText;                                     // 0xB60(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, EditFixedSize, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             SaddleCheck;                                       // 0xB68(0x8)(Edit, Net, Parm, OutParm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             TameCheck;                                         // 0xB70(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, Parm, OutParm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UButton*                               ToDinosButton;                                     // 0xB78(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, OutParm, Config, EditConst, SubobjectReference)
	int32                                        ScreenTracker;                                     // 0xB80(0x4)(ExportObject, Net, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	uint8                                        Pad_3BCF[0x4];                                     // Fixing Size After Last Property  > TateDumper <
	TArray<class FText>                          FolderNames;                                       // 0xB88(0x10)(Edit, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class UUI_DebugSpawnMenuEntry*>       DebugEntries;                                      // 0xB98(0x10)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        DinoNames;                                         // 0xBA8(0x10)(ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, OutParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        DinoEggNames;                                      // 0xBB8(0x10)(BlueprintReadOnly, EditFixedSize, Parm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        CheatNames;                                        // 0xBC8(0x10)(BlueprintVisible, Net, Parm, ZeroConstructor, Config, EditConst, SubobjectReference)
	TArray<class FString>                        CheatStrings;                                      // 0xBD8(0x10)(ExportObject, Parm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        CharacterPresetStrings;                            // 0xBE8(0x10)(BlueprintVisible, BlueprintReadOnly, EditFixedSize, OutParm, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<struct FCheatMenuCharacterLevelPreset> CharacterPresetLevel;                              // 0xBF8(0x10)(ExportObject, BlueprintReadOnly, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        ScorchedEarthDinoNames;                            // 0xC08(0x10)(ExportObject, EditFixedSize, Parm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<enum class ECheatMenuOptionTypes>     OptionTypes;                                       // 0xC18(0x10)(Edit, ConstParm, BlueprintVisible, ExportObject, Parm, OutParm, ZeroConstructor, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ScorchedEarthEggNames;                             // 0xC28(0x10)(ConstParm, BlueprintVisible, BlueprintReadOnly, Net, OutParm, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             IslandMapJumpInfos;                                // 0xC38(0x10)(Edit, ExportObject, EditFixedSize, Parm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        MapOpenCheats;                                     // 0xC48(0x10)(Edit, BlueprintVisible, ExportObject, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        OpenMapNames;                                      // 0xC58(0x10)(Net, Parm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             SE_MapJumpInfos;                                   // 0xC68(0x10)(Edit, ConstParm, BlueprintReadOnly, Net, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        ReferenceTexts;                                    // 0xC78(0x10)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, EditFixedSize, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             CenterMapJumpInfos;                                // 0xC88(0x10)(BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             AberrationMapJumpInfos;                            // 0xC98(0x10)(ConstParm, BlueprintVisible, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             RagnarokMapJumpInfos;                              // 0xCA8(0x10)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             ExtinctionMapJumpInfos;                            // 0xCB8(0x10)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             ValgueroMapJumpInfos;                              // 0xCC8(0x10)(ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             CrystalIslesMapJumpInfos;                          // 0xCD8(0x10)(ConstParm, BlueprintVisible, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             GenesisMapJumpInfos;                               // 0xCE8(0x10)(ConstParm, ExportObject, EditFixedSize, Parm, OutParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             Gen2MapJumpInfos;                                  // 0xCF8(0x10)(ConstParm, ExportObject, BlueprintReadOnly, Net, OutParm, ZeroConstructor, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             LostIslandMapJumpInfos;                            // 0xD08(0x10)(ZeroConstructor, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<bool>                                 CheatConfirmation;                                 // 0xD18(0x10)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        IslandBossStrings;                                 // 0xD28(0x10)(Edit, ConstParm, BlueprintVisible, ExportObject, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        IslandBossCheats;                                  // 0xD38(0x10)(BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        SEBossCheats;                                      // 0xD48(0x10)(Edit, ConstParm, BlueprintVisible, Net, EditFixedSize, OutParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        SEBossStrings;                                     // 0xD58(0x10)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, OutParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        AberrationBossStrings;                             // 0xD68(0x10)(ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, Config, EditConst, SubobjectReference)
	TArray<class FString>                        AberrationBossCheats;                              // 0xD78(0x10)(Edit, ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtinctionBossCheats;                              // 0xD88(0x10)(Edit, ExportObject, Net, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtinctionBossStrings;                             // 0xD98(0x10)(Edit, ConstParm, BlueprintVisible, ExportObject, EditFixedSize, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        CenterBossCheats;                                  // 0xDA8(0x10)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        CenterBossStrings;                                 // 0xDB8(0x10)(ConstParm, BlueprintVisible, ExportObject, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        RagnarokBossCheats;                                // 0xDC8(0x10)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        RagnarokBossStrings;                               // 0xDD8(0x10)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ValgueroBossCheats;                                // 0xDE8(0x10)(ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ValgueroBossStrings;                               // 0xDF8(0x10)(Edit, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        AberrationUniqueDinoNames;                         // 0xE08(0x10)(Edit, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, OutParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        AberrantDinoNames;                                 // 0xE18(0x10)(ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, ZeroConstructor, Config, EditConst, SubobjectReference)
	TArray<class FString>                        Community_Dino_Names;                              // 0xE28(0x10)(Edit, BlueprintVisible, Net, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        ExtinctionDinoNames;                               // 0xE38(0x10)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtinctionCorruptDinoNames;                        // 0xE48(0x10)(ExportObject, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	TArray<bool>                                 OptionsIsEngram;                                   // 0xE58(0x10)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, Parm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<int32>                                OptionsQuantity;                                   // 0xE68(0x10)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtionctionEggNames;                               // 0xE78(0x10)(ConstParm, Net, Parm, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        EventDinoNames;                                    // 0xE88(0x10)(Edit, ConstParm, BlueprintVisible, Net, Parm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	class FString                                FilterName;                                        // 0xE98(0x10)(BlueprintReadOnly, Net, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	bool                                         IgnoreFilterChange;                                // 0xEA8(0x1)(ExportObject, EditFixedSize, DisableEditOnTemplate, Config, EditConst, SubobjectReference)

	static class UClass* StaticClass();
	static class UCheatMenu_C* GetDefaultObj();

	bool BPEscapeClosed(class AShooterHUD** CallFunc_GetShooterHUD_ReturnValue, bool CallFunc_CloseSpawnMenu_ReturnValue);
	void ClearFilter(bool* ShouldRefresh);
	bool GetBossSpawnArray(const TArray<class FString>& BossNames, const TArray<class FString>& BossCheats, class UWorld** CallFunc_GetGameWorld_ReturnValue);
	void CloseMenu(class AShooterHUD** CallFunc_GetShooterHUD_ReturnValue, bool CallFunc_CloseSpawnMenu_ReturnValue);
	bool GetMapOpenListsForEntry(const TArray<class FString>& CheatStrings, bool Success);
	class UCheatMenuMapOpenButton_C* CreateMapOpenButton(class FString* Name, class FText CallFunc_Conv_StringToText_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue);
	class UUI_DebugSpawnMenuEntry* CreateMapOpenEntry(class FString* Name, int32 ArrayIndex, TArray<class FString>* Array, class FString* CallFunc_Array_Get_Item, int32* CallFunc_Array_Add_ReturnValue);
	class FString GetMapJumpArray(int32* Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool* CallFunc_GetMapJumpListForEntry_Success, int32* CallFunc_Array_Length_ReturnValue, int32* CallFunc_Array_Add_ReturnValue);
	class UCheatMapJumpButton_C* CreateMapJumpButton(class APlayerController* CallFunc_GetPlayerController_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue);
	TArray<struct FCheatMapJumpInfo> CreateMapJumpEntry(int32 ArrayIndex, struct FCheatMapJumpInfo* CallFunc_Array_Get_Item, class UUI_DebugSpawnMenuEntry** CallFunc_CreateMapJumpButton_CreatedWidget, int32* CallFunc_Array_Add_ReturnValue);
	bool GetMapJumpListForEntry(bool Success, class UWorld** CallFunc_GetGameWorld_ReturnValue);
	bool AddAllEntriesButtonForItems(enum class ECheatMenuOptionTypes* CallFunc_Array_Get_Item);
	class UCheatMenuItemAllButton_C* CreateButtonFromAllEntries();
	void HideAllOptions();
	bool SetupOptionsBarForFolder(bool Temp_bool_Variable, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, bool Temp_bool_Variable_1, enum class ESlateVisibility Temp_byte_Variable_2, enum class ESlateVisibility Temp_byte_Variable_3, bool Temp_bool_Variable_2, enum class ESlateVisibility Temp_byte_Variable_4, enum class ESlateVisibility Temp_byte_Variable_5, bool Temp_bool_Variable_3, enum class ESlateVisibility Temp_byte_Variable_6, enum class ESlateVisibility Temp_byte_Variable_7, bool Temp_bool_Variable_4, enum class ESlateVisibility Temp_byte_Variable_8, enum class ESlateVisibility Temp_byte_Variable_9, enum class ECheatMenuOptionTypes* CallFunc_Array_Get_Item, enum class ESlateVisibility* K2Node_Select_Default, enum class ESlateVisibility* K2Node_Select_Default_1, enum class ESlateVisibility* K2Node_Select_Default_2, enum class ESlateVisibility* K2Node_Select_Default_3, enum class ESlateVisibility* K2Node_Select_Default_4);
	bool GetCharacterPresetsForEntry(TArray<struct FCheatMenuCharacterPresetItems>* CharacterPresetItem, bool Success);
	bool GetCheatListsForEntry(const TArray<class FString>& CheatStrings, TArray<bool>* RequireConfirm, bool* AllowAdditionalString, bool Success, const TArray<class FString>& CallFunc_GetBossSpawnArray_BossCheats);
	bool GetEggListsForEntry(TArray<TSoftClassPtr<class UPrimalItem>>* DinoEggBlueprintIDs, TArray<TSoftClassPtr<class UPrimalItem>>* DinoFertEggBlueprintIDs, bool Success);
	bool GetDinoListsForEntry(const TArray<TSoftClassPtr<class APrimalDinoCharacter>>& Dinos, const TArray<TSoftClassPtr<class UPrimalItem>>& Saddles, bool Success);
	class UUI_DebugSpawnMenuEntry* CreateCharacterPresetEntry(int32 ArrayIndex, struct FCheatMenuCharacterPresetItems* CallFunc_Array_Get_Item, struct FCheatMenuCharacterLevelPreset* CallFunc_Array_Get_Item_1, class FText CallFunc_Conv_StringToText_ReturnValue, int32* CallFunc_Array_Add_ReturnValue);
	class UUI_DebugSpawnMenuEntry* CreateCheatEntry(class FString* Name, int32 ArrayIndex, TArray<class FString>* Array, TArray<bool>* ArrayConfirm, bool* AllowAdditionalString, bool Temp_bool_Variable, bool* CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, class FString* CallFunc_Array_Get_Item_1, bool Temp_bool_Variable_1, bool* K2Node_Select_Default, int32* CallFunc_Array_Add_ReturnValue);
	class UUI_DebugSpawnMenuEntry* CreateEggEntry(class FString* Name, int32 ArrayIndex, TSoftClassPtr<class UPrimalItem>* CallFunc_Array_Get_Item, bool CallFunc_IsValidSoftClassReference_ReturnValue, TSoftClassPtr<class UPrimalItem>* CallFunc_Array_Get_Item_1, bool CallFunc_IsValidSoftClassReference_ReturnValue_1, bool Temp_bool_Variable, class FString* K2Node_Select_Default, const class FString& CallFunc_Concat_StrStr_ReturnValue, int32* CallFunc_Array_Add_ReturnValue);
	class UCheatMenuButton_C* CreateDinoEntry(int32 ArrayIndex, TSoftClassPtr<class UPrimalItem>* CallFunc_Array_Get_Item, TSoftClassPtr<class APrimalDinoCharacter>* CallFunc_Array_Get_Item_1, bool CallFunc_IsValidSoftClassReference_ReturnValue, int32* CallFunc_Array_Add_ReturnValue);
	void SetupOptionBar(int32* CallFunc_Array_Get_Item, bool* CallFunc_Array_Get_Item_1, class FText CallFunc_Conv_IntToText_ReturnValue);
	class UCheatMenuCharacterPresetsButton_C* CreateButtonFromCharacterPresets(class FText* Name, class APlayerController* CallFunc_GetPlayerController_ReturnValue, bool* CallFunc_IsValid_ReturnValue);
	class UCheatMenuFolderButton_C* CreateFolderButtons(class FText* Name, int32 ScreenNumber, class UTexture2D** Image, class UUI_DebugSpawnMenuEntry** OutWidget, class APlayerController* CallFunc_GetPlayerController_ReturnValue);
	class UCheatMenuCheatButton_C* CreateCheatButtonFromBlueprintID(class FString* Name, bool* RequireConfirm, class FText CallFunc_Conv_StringToText_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue);
	class UPrimalItem* CreateEggItemButtonFromBlueprintIDs(class FString* Name, TSoftClassPtr<class UPrimalItem>* FertilizedEgg, bool Temp_bool_Variable, class UClass* CallFunc_ClassAssetResolve_ReturnValue, class UClass* CallFunc_ClassAssetResolve_ReturnValue_1, class FText CallFunc_Conv_StringToText_ReturnValue, bool CallFunc_IsValidClass_ReturnValue, class UClass** K2Node_Select_Default, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsPrimal_Item, bool* K2Node_DynamicCast_bSuccess, bool* CallFunc_IsValid_ReturnValue, bool* CallFunc_IsValid_ReturnValue_1);
	class UCheatMenuItemButton_C* CreateItemButtonFromBlueprintID(TSoftClassPtr<class UPrimalItem>* Blueprint, bool CallFunc_IsValidSoftClassReference_ReturnValue, class UClass* CallFunc_ClassAssetResolve_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsPrimal_Item, class APlayerController* CallFunc_GetPlayerController_ReturnValue);
	class UCheatMenuItemButton_C* CreateItemButtonAndSetText(const class FString& ItemSpawnString, class UCheatMenuButton_C** CreatedButton, class FText CallFunc_Conv_StringToText_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue);
	class UCheatMenuButton_C* CreateDinoButtonAndSetText(TSoftClassPtr<class APrimalDinoCharacter>* DinoBP, TSoftClassPtr<class UPrimalItem>* Saddle, class UCheatMenuButton_C** CreatedButton, class FText CallFunc_Conv_StringToText_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue);
	void Construct();
	void BndEvt__CloseButton_K2Node_ComponentBoundEvent_126_OnButtonClickedEvent__DelegateSignature();
	enum class ETextCommit BndEvt__EditableTextBox_139_K2Node_ComponentBoundEvent_360_OnEditableTextBoxCommittedEvent__DelegateSignature();
	enum class ETextCommit BndEvt__DinoSpawnLevelBox_K2Node_ComponentBoundEvent_41_OnEditableTextBoxCommittedEvent__DelegateSignature();
	void BndEvt__ToDinosButton_K2Node_ComponentBoundEvent_319_OnButtonPressedEvent__DelegateSignature();
	enum class ETextCommit BndEvt__NumberEggsToSpawn_K2Node_ComponentBoundEvent_232_OnEditableTextBoxCommittedEvent__DelegateSignature();
	int32 Screen_Changed();
	void OnHome();
	bool BndEvt__BlueprintCheckBox_K2Node_ComponentBoundEvent_19_OnCheckBoxComponentStateChanged__DelegateSignature();
	bool BndEvt__SpawnMenu_TameCheck_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature();
	class FText BndEvt__CheatMenu_NamesFilterInputField_K2Node_ComponentBoundEvent_1_OnEditableTextBoxChangedEvent__DelegateSignature();
	void BndEvt__CheatMenu_Button_131_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	bool ExecuteUbergraph_CheatMenu(int32* Temp_int_Variable, bool Temp_bool_Variable, enum class ECheckBoxState Temp_byte_Variable, enum class ECheckBoxState Temp_byte_Variable_1, bool Temp_bool_Variable_1, enum class ESlateVisibility Temp_byte_Variable_2, enum class ESlateVisibility Temp_byte_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_4, enum class ETextCommit K2Node_ComponentBoundEvent_CommitMethod_2, const class FString& CallFunc_Conv_TextToString_ReturnValue, enum class ETextCommit K2Node_ComponentBoundEvent_CommitMethod_1, int32 CallFunc_Conv_StringToInt_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, class FText CallFunc_Conv_IntToText_ReturnValue, int32 CallFunc_Conv_StringToInt_ReturnValue_1, class FText CallFunc_Conv_IntToText_ReturnValue_1, enum class ETextCommit K2Node_ComponentBoundEvent_CommitMethod, const class FString& CallFunc_Conv_TextToString_ReturnValue_2, int32 CallFunc_Conv_StringToInt_ReturnValue_2, class FText CallFunc_Conv_IntToText_ReturnValue_2, class UUI_DebugSpawnMenuEntry** CallFunc_Array_Get_Item, int32* CallFunc_Array_Length_ReturnValue, int32* K2Node_CustomEvent_ToScreen, class FText* CallFunc_Array_Get_Item_1, int32* CallFunc_Array_Length_ReturnValue_1, class UUI_DebugSpawnMenuEntry** CallFunc_Array_Get_Item_2, int32* CallFunc_Array_Length_ReturnValue_2, enum class ECheckBoxState* K2Node_Select_Default, enum class ESlateVisibility* K2Node_Select_Default_1, enum class ECheatMenuOptionTypes* CallFunc_Array_Get_Item_3, bool* CallFunc_GetEggListsForEntry_Success, TArray<class FString>* CallFunc_GetCheatListsForEntry_CheatStrings, TArray<bool>* CallFunc_GetCheatListsForEntry_RequireConfirm, const TArray<struct FCheatMenuCharacterLevelPreset>& CallFunc_GetCharacterPresetsForEntry_CharacterPresetLevel, bool CallFunc_GetCharacterPresetsForEntry_Success, bool* CallFunc_GetMapJumpListForEntry_Success, const TArray<class FString>& CallFunc_GetMapJumpArray_EmptyStringArray, const TArray<class FString>& CallFunc_GetMapOpenListsForEntry_CheatStrings, class UTexture2D** CallFunc_Array_Get_Item_4, int32* CallFunc_Array_Add_ReturnValue, class FString* CallFunc_Array_Get_Item_5, class FText CallFunc_Conv_StringToText_ReturnValue, const TArray<class FString>& CallFunc_GetBossSpawnArray_BossCheats, TArray<TSoftClassPtr<class UPrimalItem>>* K2Node_Select_Default_2, TSoftClassPtr<class UPrimalItem>* CallFunc_Array_Get_Item_6, const class FString& CallFunc_Conv_TextToString_ReturnValue_3, bool* CallFunc_IsValid_ReturnValue, int32* CallFunc_Array_Add_ReturnValue_1, int32* CallFunc_Array_Length_ReturnValue_3, int32* Temp_int_Variable_1, TArray<class FString>* K2Node_Select_Default_3, bool CallFunc_Contains_ReturnValue, class FString* CallFunc_Array_Get_Item_7, int32* CallFunc_Array_Length_ReturnValue_4, int32* CallFunc_Len_ReturnValue);
};

}


