#pragma once

// Dumped with TateDumper!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass FL_VFX_Spawn_Ground_Effect.FL_VFX_Spawn_Ground_Effect_C
class UFL_VFX_Spawn_Ground_Effect_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UFL_VFX_Spawn_Ground_Effect_C* GetDefaultObj();

	struct FVector Set_Ground_VFX_Parameters(class UNiagaraComponent** Niagara_Component, struct FVector* Location, double* Size_Mult, class UObject* __WorldContext, double* Mult_Velocity, double* Mult_Amount, double* Mult_Size, double* Thatch, double Sand, double* Pebbles, double Leaves, struct FVector* Init_Velocity, double* Impact_Mult, double Grass, double* Friction, struct FColor* Color, double* Bounce, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue_1, const struct FHitResult& CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, struct FColor* CallFunc_Find_Ground_Attributes_Color, double* CallFunc_Find_Ground_Attributes_SandAmount, double* CallFunc_Find_Ground_Attributes_DustAmount, double* CallFunc_Find_Ground_Attributes_LeavesDebrisAmount, double* CallFunc_Find_Ground_Attributes_GrassDebrisAmount, double* CallFunc_Find_Ground_Attributes_ThatchDebrisAmount, double* CallFunc_Find_Ground_Attributes_PebblesDebrisAmount, double* CallFunc_Find_Ground_Attributes_Friction, double* CallFunc_Find_Ground_Attributes_Bounce, const struct FVector& CallFunc_Multiply_VectorVector_ReturnValue, const struct FLinearColor& CallFunc_Conv_ColorToLinearColor_ReturnValue, struct FVector* CallFunc_MakeVector_ReturnValue, float* CallFunc_SetVariableFloat_InValue_ImplicitCast, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_1, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_2, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_3, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_4, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_5, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_6, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_7, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_8, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_9, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_10, double* CallFunc_MakeVector_X_ImplicitCast, double* CallFunc_MakeVector_Y_ImplicitCast, double* CallFunc_MakeVector_Z_ImplicitCast);
	struct FVector Set_Cart_Track_VFX_Parameters(class UNiagaraComponent** Niagara_System, class UObject* __WorldContext, int32* Render_Index, double* Thatch, double Sand, double* Pebbles, double Leaves, double Grass, double* Friction, struct FColor* Color, double* Bounce, double Fade_Off_Time, const struct FVector& CallFunc_ClampVectorSize_ReturnValue);
	class UObject* Find_Ground_Attributes(class UObject* __WorldContext, struct FColor* Color, double* SandAmount, double DustAmount, double* LeavesDebrisAmount, double GrassDebrisAmount, double* ThatchDebrisAmount, double* PebblesDebrisAmount, double* Friction, double* Bounce, const struct FStruct_Ground_Attributes& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, class FString* CallFunc_Conv_ObjectToString_ReturnValue, class FName* CallFunc_Conv_StringToName_ReturnValue, const struct FStruct_Ground_Attributes& CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1);
	struct FVector Spawn_Ground_VFX_Attached(class UNiagaraSystem** NS, struct FVector* Location, double* Size_Mult, struct FRotator* NS_Rotate, const class FString& Attached_Bone_Name, class USkeletalMeshComponent* Attached_Skeletal_Mesh, class UObject* __WorldContext, double* Mult_Velocity, double* Mult_Amount, double* Mult_Size, class UNiagaraComponent** Niagara_Component, double* Thatch, double Sand, double* Pebbles, double Leaves, struct FVector* Init_Velocity, double* Impact_Mult, double Grass, double* Friction, struct FColor* Color, double* Bounce, class FName* CallFunc_Conv_StringToName_ReturnValue, class FName* CallFunc_Conv_StringToName_ReturnValue_1, struct FVector* CallFunc_GetBoneLinearVelocity_ReturnValue, class FName* CallFunc_Conv_StringToName_ReturnValue_2, const struct FVector& CallFunc_GetSocketLocation_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue_1, const struct FVector& CallFunc_Add_VectorVector_ReturnValue_2, bool* CallFunc_EqualEqual_DoubleDouble_ReturnValue, const struct FHitResult& CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, struct FColor* CallFunc_Find_Ground_Attributes_Color, double* CallFunc_Find_Ground_Attributes_SandAmount, double* CallFunc_Find_Ground_Attributes_DustAmount, double* CallFunc_Find_Ground_Attributes_LeavesDebrisAmount, double* CallFunc_Find_Ground_Attributes_GrassDebrisAmount, double* CallFunc_Find_Ground_Attributes_ThatchDebrisAmount, double* CallFunc_Find_Ground_Attributes_PebblesDebrisAmount, double* CallFunc_Find_Ground_Attributes_Friction, double* CallFunc_Find_Ground_Attributes_Bounce, const struct FRotator& CallFunc_MakeRotFromYX_ReturnValue, const struct FRotator& CallFunc_ComposeRotators_ReturnValue, class UNiagaraComponent** CallFunc_SpawnSystemAttached_ReturnValue, const struct FVector& CallFunc_Multiply_VectorVector_ReturnValue, const struct FLinearColor& CallFunc_Conv_ColorToLinearColor_ReturnValue, struct FVector* CallFunc_MakeVector_ReturnValue, float* CallFunc_SetVariableFloat_InValue_ImplicitCast, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_1, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_2, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_3, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_4, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_5, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_6, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_7, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_8, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_9, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_10, double* CallFunc_MakeVector_X_ImplicitCast, double* CallFunc_MakeVector_Y_ImplicitCast, double* CallFunc_MakeVector_Z_ImplicitCast);
	struct FVector Spawn_Ground_VFX(class UNiagaraSystem** NS, struct FVector* Location, double* Size_Mult, struct FRotator* NS_Rotate, class UObject* __WorldContext, double* Mult_Velocity, double* Mult_Amount, double* Mult_Size, class UNiagaraComponent** Niagara_Component, double* Thatch, double Sand, double* Pebbles, double Leaves, struct FVector* Init_Velocity, double* Impact_Mult, double Grass, double* Friction, struct FColor* Color, double* Bounce, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue_1, const struct FVector& CallFunc_Multiply_VectorVector_ReturnValue, const struct FLinearColor& CallFunc_Conv_ColorToLinearColor_ReturnValue, const struct FHitResult& CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, struct FVector* CallFunc_MakeVector_ReturnValue, struct FColor* CallFunc_Find_Ground_Attributes_Color, double* CallFunc_Find_Ground_Attributes_SandAmount, double* CallFunc_Find_Ground_Attributes_DustAmount, double* CallFunc_Find_Ground_Attributes_LeavesDebrisAmount, double* CallFunc_Find_Ground_Attributes_GrassDebrisAmount, double* CallFunc_Find_Ground_Attributes_ThatchDebrisAmount, double* CallFunc_Find_Ground_Attributes_PebblesDebrisAmount, double* CallFunc_Find_Ground_Attributes_Friction, double* CallFunc_Find_Ground_Attributes_Bounce, struct FRotator* CallFunc_Conv_VectorToRotator_ReturnValue, const struct FRotator& CallFunc_ComposeRotators_ReturnValue, class UNiagaraComponent** CallFunc_SpawnSystemAtLocation_ReturnValue, float* CallFunc_SetVariableFloat_InValue_ImplicitCast, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_1, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_2, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_3, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_4, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_5, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_6, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_7, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_8, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_9, float* CallFunc_SetVariableFloat_InValue_ImplicitCast_10, double* CallFunc_MakeVector_X_ImplicitCast, double* CallFunc_MakeVector_Y_ImplicitCast, double* CallFunc_MakeVector_Z_ImplicitCast);
};

}


