#pragma once

// Dumped with TateDumper!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass NinjaLiveFunctions.NinjaLiveFunctions_C
class UNinjaLiveFunctions_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UNinjaLiveFunctions_C* GetDefaultObj();

	struct FHitResult CameraFacing(class USceneComponent* InMesh, bool* UseLegacyFacing, bool LockY, struct FRotator* TraceMeshInitRot, class UObject* __WorldContext, bool Temp_bool_Variable, class APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, const struct FRotator& CallFunc_GetCameraRotation_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FRotator& CallFunc_ComposeRotators_ReturnValue, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue, bool Temp_bool_Variable_1, struct FRotator* CallFunc_FindLookAtRotation_ReturnValue, float* CallFunc_BreakRotator_Roll, float* CallFunc_BreakRotator_Pitch, float* CallFunc_BreakRotator_Yaw, double* CallFunc_Add_DoubleDouble_ReturnValue, const struct FRotator& CallFunc_ComposeRotators_ReturnValue_1, double* CallFunc_Add_DoubleDouble_ReturnValue_1, const struct FRotator& K2Node_Select_Default, const struct FRotator& K2Node_Select_Default_1, double* CallFunc_Add_DoubleDouble_A_ImplicitCast, double* CallFunc_Add_DoubleDouble_A_ImplicitCast_1, float* CallFunc_MakeRotator_Yaw_ImplicitCast, float* CallFunc_MakeRotator_Roll_ImplicitCast);
	double RenderTgAcquisitionStatus(class UObject** SelfRef, int32* RT_number_Minus_added, enum class ESimPrecision_Enum* SimPrecision, int32 ResX, int32 ResY, bool PoolManDetected, bool* HalfRes, class UObject* __WorldContext, const class FString& Print, double MemConsumtion, int32* CallFunc_MakeLiteralInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32* Temp_int_Variable, int32* Temp_int_Variable_1, const class FString& K2Node_Select_Default, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, const class FString& CallFunc_Concat_StrStr_ReturnValue_4, const class FString& CallFunc_Concat_StrStr_ReturnValue_5, const class FString& CallFunc_Concat_StrStr_ReturnValue_6, const class FString& CallFunc_Concat_StrStr_ReturnValue_7, const class FString& CallFunc_Concat_StrStr_ReturnValue_8, const class FString& CallFunc_Concat_StrStr_ReturnValue_9, int32* Temp_int_Variable_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_10, enum class ESimPrecision_Enum Temp_byte_Variable, int32 K2Node_Select_Default_1, double* CallFunc_Multiply_IntFloat_ReturnValue);
	struct FRenderTargetListItem AcquireRenderTargetsFromPool(int32* Request_0_RGBA__1_RG__2_R_, int32* HostMinusRenderTGMinusListMinusIndex, class ANinjaLive_MemoryPoolManager_C* MemoryPoolManager, class UObject* __WorldContext, TMap<class FString, class UTextureRenderTarget2D*> RenderTargetsMapTmp, TMap<class FString, class UTextureRenderTarget2D*> RenderTargetsMap, const class FString& CallFunc_Array_Get_Item, bool Temp_bool_Variable, int32* Temp_int_Variable, int32* Temp_int_Variable_1, const TArray<struct FRenderTargetListItem>& K2Node_Select_Default, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue);
	bool TemplateLoader(class FName* TemplateDefinition, class UDataTable* LoadedDataTable, const class FString& LoadedDatatablePath, class UObject* __WorldContext, bool LoadFailed, class UObject* LoadedTemplateObject, const class FString& LoadedTmpFullPath, const class FString& LoadedTemplateNameOnly, bool* UsesAbsolutePath, bool* InvalidObjectIndicator, bool* RowMissingIndicator, TArray<struct FAssetData>* K2Node_MakeArray_Array, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, int32 CallFunc_Len_ReturnValue, int32* CallFunc_FindSubstring_ReturnValue, bool* CallFunc_StartsWith_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_EqualEqual_StrStr_ReturnValue, class FString* CallFunc_RightChop_ReturnValue, int32 Temp_int_Array_Index_Variable, bool CallFunc_EqualEqual_StriStri_ReturnValue, bool Temp_bool_Variable, int32 Temp_int_Loop_Counter_Variable, const TArray<struct FAssetData>& CallFunc_GetAssetsByPackageName_OutAssetData, bool CallFunc_GetAssetsByPackageName_ReturnValue, bool* CallFunc_EqualEqual_IntInt_ReturnValue, const TArray<struct FAssetData>& K2Node_Select_Default, const struct FAssetData& CallFunc_Array_Get_Item);
	class FString SingleKeyPicker(class UDataTable** DataTableIn, const class FString& KeyToPick, class UObject* __WorldContext, const class FString& PickedKeyValue, bool NotFound, bool* RowNotFound, const class FString& CallFunc_Concat_StrStr_ReturnValue);
	class UTextureRenderTarget2D* CreateRenderTarget(int32* Width, int32* Height, enum class ETextureRenderTargetFormat* Format, class UObject* __WorldContext, class UTextureRenderTarget2D** RTout, enum class ETextureAddress Temp_byte_Variable, enum class ETextureAddress Temp_byte_Variable_1, bool Temp_bool_Variable, enum class ETextureAddress K2Node_Select_Default);
	bool PresetLoader(class FString* PresetName, TArray<class FName>* AssetPath, bool* ForcePreferredPreset, class UDataTable* PreferredPreset, class UObject* __WorldContext, class UDataTable* LoadedDataTable, const class FString& LoadedDatatablePath, TMap<class FString, double> PresetMap, TMap<class FString, double> PresetMapTemp, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, int32 Temp_int_Array_Index_Variable, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, TArray<struct FAssetData>* K2Node_MakeArray_Array, int32 Temp_int_Loop_Counter_Variable, int32 Temp_int_Array_Index_Variable_1, TSet<class FName> K2Node_MakeSet_Set, TArray<class FName>* K2Node_MakeArray_Array_1, TArray<class FName>* K2Node_MakeArray_Array_2, bool Temp_bool_Variable, bool Temp_bool_Variable_1, struct FARFilter* CallFunc_MakeARFilter_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_GetAssets_ReturnValue, bool* CallFunc_EqualEqual_IntInt_ReturnValue, const TArray<struct FAssetData>& K2Node_Select_Default, const struct FAssetData& CallFunc_Array_Get_Item, class UDataTable** K2Node_DynamicCast_AsData_Table, bool* K2Node_DynamicCast_bSuccess, class UDataTable* K2Node_Select_Default_1, const TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, class FName CallFunc_Array_Get_Item_1, class FText* CallFunc_Conv_DoubleToText_ReturnValue, const class FString& CallFunc_Replace_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_4);
	struct FLinearColor TraceOverlap(struct FVector* Start, struct FVector* End, double* TracelineOvershoot, TArray<class AActor*>* FluidNinjaLIVEActors, class UObject* __WorldContext, struct FLinearColor* HitUV, struct FVector* TracePosition, struct FVector* CallFunc_Subtract_VectorVector_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool* CallFunc_BreakHitResult_bInitialOverlap, float* CallFunc_BreakHitResult_Distance, struct FVector* CallFunc_BreakHitResult_Location, struct FVector* CallFunc_BreakHitResult_ImpactPoint, struct FVector* CallFunc_BreakHitResult_Normal, struct FVector* CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial** CallFunc_BreakHitResult_PhysMat, class AActor** CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent** CallFunc_BreakHitResult_HitComponent, class FName* CallFunc_BreakHitResult_HitBoneName, class FName* CallFunc_BreakHitResult_BoneName, int32* CallFunc_BreakHitResult_HitItem, int32* CallFunc_BreakHitResult_ElementIndex, int32* CallFunc_BreakHitResult_FaceIndex);
	struct FLinearColor TraceMouse(bool* TouchSensitive, uint8* FingerIndex, TArray<class AActor*>* FluidNinjaLIVEActors, class UObject* __WorldContext, struct FLinearColor* HitUV, bool* SimHitByMouse, bool MouseClickValid, bool* TouchValid, bool Temp_bool_Variable, const struct FHitResult& CallFunc_GetHitResultUnderCursorByChannel_HitResult, bool CallFunc_GetHitResultUnderCursorByChannel_ReturnValue, class APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FHitResult& CallFunc_GetHitResultUnderFingerByChannel_HitResult, bool CallFunc_GetHitResultUnderFingerByChannel_ReturnValue, const struct FHitResult& K2Node_Select_Default, bool CallFunc_BreakHitResult_bBlockingHit, bool* CallFunc_BreakHitResult_bInitialOverlap, float* CallFunc_BreakHitResult_Distance, struct FVector* CallFunc_BreakHitResult_Location, struct FVector* CallFunc_BreakHitResult_ImpactPoint, struct FVector* CallFunc_BreakHitResult_Normal, struct FVector* CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial** CallFunc_BreakHitResult_PhysMat, class AActor** CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent** CallFunc_BreakHitResult_HitComponent, class FName* CallFunc_BreakHitResult_HitBoneName, class FName* CallFunc_BreakHitResult_BoneName, int32* CallFunc_BreakHitResult_HitItem, int32* CallFunc_BreakHitResult_ElementIndex, int32* CallFunc_BreakHitResult_FaceIndex, bool CallFunc_BreakHitResult_bBlockingHit_1, bool* CallFunc_BreakHitResult_bInitialOverlap_1, float* CallFunc_BreakHitResult_Distance_1, struct FVector* CallFunc_BreakHitResult_Location_1, struct FVector* CallFunc_BreakHitResult_ImpactPoint_1, struct FVector* CallFunc_BreakHitResult_Normal_1, struct FVector* CallFunc_BreakHitResult_ImpactNormal_1, class UPhysicalMaterial** CallFunc_BreakHitResult_PhysMat_1, class AActor** CallFunc_BreakHitResult_HitActor_1, class UPrimitiveComponent** CallFunc_BreakHitResult_HitComponent_1, class FName* CallFunc_BreakHitResult_HitBoneName_1, class FName* CallFunc_BreakHitResult_BoneName_1, int32* CallFunc_BreakHitResult_HitItem_1, int32* CallFunc_BreakHitResult_ElementIndex_1, int32* CallFunc_BreakHitResult_FaceIndex_1);
};

}


