#pragma once

// Dumped with TateDumper!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x491 (0x10C1 - 0xC30)
// WidgetBlueprintGeneratedClass TribeManagerUI.TribeManagerUI_C
class UTribeManagerUI_C : public UUI_TribeManager
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xC30(0x8)(Edit, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, SubobjectReference)
	class UWidgetAnimation*                      Close;                                             // 0xC38(0x8)(ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, Config, DisableEditOnInstance, EditConst)
	class UWidgetAnimation*                      Open;                                              // 0xC40(0x8)(BlueprintVisible, BlueprintReadOnly, EditFixedSize, OutParm, Transient, Config, EditConst)
	class UCustomButtonWidget*                   AcceptWarButton;                                   // 0xC48(0x8)(Edit, Parm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  AccessInventoryRankVariableSlider;                 // 0xC50(0x8)(ConstParm, BlueprintVisible, ExportObject, Net, EditFixedSize, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  AccessStructureRankVariableSlider;                 // 0xC58(0x8)(ExportObject, EditFixedSize, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   AddNewGroupRankButton;                             // 0xC60(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, EditFixedSize, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UScaleBox*                             AlliancesEnabledEffect;                            // 0xC68(0x8)(ConstParm, BlueprintVisible, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* ALLOWBANISHMENTS_bool;                             // 0xC70(0x8)(Edit, ConstParm, Net, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* ALLOWDEMOTIONS_bool;                               // 0xC78(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* ALLOWINVITES_bool;                                 // 0xC80(0x8)(Edit, ExportObject, BlueprintReadOnly, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* ALLOWPROMOTIONS_bool;                              // 0xC88(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   ApplyGroupRankSettingsButton;                      // 0xC90(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UHorizontalBox*                        BG;                                                // 0xC98(0x8)(Edit, ConstParm, ExportObject, Net, Parm, ReturnParm, Transient, EditConst, GlobalConfig, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* CANPING_bool;                                      // 0xCA0(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, EditFixedSize, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* CanRallyPoint_Slider;                              // 0xCA8(0x8)(Edit, ConstParm, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UButton*                               CloseButton;                                       // 0xCB0(0x8)(Edit, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, Config, DisableEditOnInstance, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   CloseGroupRanksButton;                             // 0xCB8(0x8)(Edit, ExportObject, BlueprintReadOnly, Net, Parm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UComboBoxString*                       Combo_TribeGovern_DinoOwnership;                   // 0xCC0(0x8)(Edit, BlueprintVisible, EditFixedSize, Parm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UComboBoxString*                       Combo_TribeGovern_DinoTaming;                      // 0xCC8(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UComboBoxString*                       Combo_TribeGovern_DinoUnclaiming;                  // 0xCD0(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UComboBoxString*                       Combo_TribeGovern_PINCode;                         // 0xCD8(0x8)(Edit, ConstParm, Net, EditFixedSize, Parm, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UComboBoxString*                       Combo_TribeGovern_StructureOwnership;              // 0xCE0(0x8)(Edit, BlueprintVisible, ExportObject, EditFixedSize, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   CreateNewAllianceButton;                           // 0xCE8(0x8)(Edit, ConstParm, ExportObject, BlueprintReadOnly, Parm, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   CreateTribeButton;                                 // 0xCF0(0x8)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UImage*                                CreatureOwnershipBottomBorder;                     // 0xCF8(0x8)(ExportObject, BlueprintReadOnly, EditFixedSize, EditConst, InstancedReference, SubobjectReference)
	class UImage*                                CreatureOwnershipTopBorder;                        // 0xD00(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* DEFAULTTRIBEGROUP_bool;                            // 0xD08(0x8)(Edit, ExportObject, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   DeleteGroupRankButton;                             // 0xD10(0x8)(Edit, ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   ExitAlliancesButton;                               // 0xD18(0x8)(ConstParm, Net, ZeroConstructor, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UImage*                                FrontOverlayAdditive;                              // 0xD20(0x8)(ConstParm, BlueprintReadOnly, Parm, DisableEditOnTemplate, Transient, EditConst, GlobalConfig, SubobjectReference)
	class UButton*                               GoToAlliances;                                     // 0xD28(0x8)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UButton*                               GoToGovernance;                                    // 0xD30(0x8)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UButton*                               GoToGroups;                                        // 0xD38(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, ZeroConstructor, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UButton*                               GoToTribeLog;                                      // 0xD40(0x8)(Edit, ConstParm, ExportObject, BlueprintReadOnly, ZeroConstructor, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UButton*                               GoToTribes;                                        // 0xD48(0x8)(Edit, ConstParm, ExportObject, Net, EditFixedSize, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UButton*                               GoToWarfare;                                       // 0xD50(0x8)(ConstParm, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UScaleBox*                             GovernanceEnabledEffect;                           // 0xD58(0x8)(Edit, BlueprintVisible, ExportObject, EditFixedSize, Parm, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UVerticalBox*                          GroupChangeAdminPanel;                             // 0xD60(0x8)(Net, EditFixedSize, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UComboBoxString*                       GroupRankComboBox;                                 // 0xD68(0x8)(Edit, ConstParm, BlueprintReadOnly, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UComboBoxString*                       GroupRankComboBoxSelector;                         // 0xD70(0x8)(Edit, ConstParm, ExportObject, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingMaxBanishmentGroupRankEditBox;     // 0xD78(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsActivationRankEditBox;            // 0xD80(0x8)(ExportObject, Net, Parm, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsAllowBanishmentsCheckbox;         // 0xD88(0x8)(BlueprintVisible, Net, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsAllowDemotionsCheckbox;           // 0xD90(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsAllowInvitesCheckbox;             // 0xD98(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsAllowPromotionsCheckbox;          // 0xDA0(0x8)(ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsDefaultActivationRankEditBox;     // 0xDA8(0x8)(Edit, ConstParm, BlueprintVisible, Net, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsDefaultInventoryRankEditBox;      // 0xDB0(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsDefaultRankCheckbox;              // 0xDB8(0x8)(Edit, ConstParm, BlueprintReadOnly, EditFixedSize, ZeroConstructor, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsGroupRankEditBox;                 // 0xDC0(0x8)(ConstParm, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsInventoryRankEditBox;             // 0xDC8(0x8)(Edit, ConstParm, Net, EditFixedSize, Parm, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsInviteToGroupRankEditBox;         // 0xDD0(0x8)(BlueprintVisible, ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsLimitInvitesCheckbox;             // 0xDD8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsMaxDemotionGroupRankEditBox;      // 0xDE0(0x8)(Edit, ExportObject, Net, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsMaxPromotionGroupRankEditBox;     // 0xDE8(0x8)(ConstParm, BlueprintVisible, Net, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsNameEditBox;                      // 0xDF0(0x8)(Edit, ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsNumInvitesRemainingEditBox;       // 0xDF8(0x8)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsPetOrderRankEditBox;              // 0xE00(0x8)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsPetRidingRankEditBox;             // 0xE08(0x8)(BlueprintVisible, BlueprintReadOnly, Net, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsPetUnclaimCheckbox;               // 0xE10(0x8)(BlueprintReadOnly, EditFixedSize, Parm, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsStructureAttachmentCheckbox;      // 0xE18(0x8)(Edit, ConstParm, BlueprintVisible, Net, EditFixedSize, Parm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsStructureBuildInRangeCheckbox;    // 0xE20(0x8)(ConstParm, Net, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCheckBox*                             GroupRankSettingsStructureDemolishCheckbox;        // 0xE28(0x8)(BlueprintReadOnly, EditFixedSize, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsTeleportDinosRankEditBox;         // 0xE30(0x8)(BlueprintReadOnly, EditFixedSize, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      GroupRankSettingsTeleportMembersRankEditBox;       // 0xE38(0x8)(Edit, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UScaleBox*                             GroupsEnableEffect;                                // 0xE40(0x8)(Edit, ConstParm, BlueprintVisible, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  HLNATELEPORTDINOSRANK_SLIDER;                      // 0xE48(0x8)(ConstParm, ExportObject, BlueprintReadOnly, Net, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  HLNATELEPORTMEMBERSRANK_SLIDER;                    // 0xE50(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, EditFixedSize, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UImage*                                IconImage;                                         // 0xE58(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, ReturnParm, Config, DisableEditOnInstance, SubobjectReference)
	class UImage*                                Image;                                             // 0xE60(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance)
	class UImage*                                Image_1;                                           // 0xE68(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, Interp)
	class UImage*                                Image_2;                                           // 0xE70(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp)
	class UImage*                                Image_3;                                           // 0xE78(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, NonTransactional)
	class UImage*                                Image_4;                                           // 0xE80(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, NonTransactional)
	class UImage*                                Image_6;                                           // 0xE88(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp, NonTransactional)
	class UImage*                                Image_42;                                          // 0xE90(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp, EditorOnly)
	class UImage*                                Image_82;                                          // 0xE98(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp, NoDestructor, AutoWeak)
	class UImage*                                Image_117;                                         // 0xEA0(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, Interp, NonTransactional, NoDestructor, AutoWeak)
	class UImage*                                Image_145;                                         // 0xEA8(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, Interp, NoDestructor, ContainsInstancedReference)
	class UImage*                                Image_151;                                         // 0xEB0(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, EditorOnly, NoDestructor, ContainsInstancedReference)
	class UImage*                                Image_154;                                         // 0xEB8(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp, EditorOnly, NoDestructor, ContainsInstancedReference)
	class UImage*                                Image_164;                                         // 0xEC0(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, NonTransactional, ContainsInstancedReference)
	class UImage*                                Image_175;                                         // 0xEC8(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, NoDestructor, ContainsInstancedReference)
	class UImage*                                Image_553;                                         // 0xED0(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, Interp, EditorOnly, SimpleDisplay)
	class UImage*                                Image_1174;                                        // 0xED8(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp, NonTransactional, NoDestructor, ContainsInstancedReference, AdvancedDisplay)
	class UImage*                                Image_1277;                                        // 0xEE0(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, Interp, NonTransactional, EditorOnly, NoDestructor, AutoWeak, ContainsInstancedReference, AdvancedDisplay)
	class UImage*                                Image_1295;                                        // 0xEE8(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, NoDestructor, AssetRegistrySearchable, AdvancedDisplay)
	class UImage*                                Image_1296;                                        // 0xEF0(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, NoDestructor, AssetRegistrySearchable, AdvancedDisplay)
	class UImage*                                Image_1297;                                        // 0xEF8(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, Interp, NoDestructor, AssetRegistrySearchable, AdvancedDisplay)
	class UImage*                                Image_1298;                                        // 0xF00(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp, NoDestructor, AssetRegistrySearchable, AdvancedDisplay)
	class UImage*                                Image_1550;                                        // 0xF08(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp, NonTransactional, EditorOnly, SimpleDisplay, AdvancedDisplay)
	class UImage*                                Image_1551;                                        // 0xF10(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, NoDestructor, SimpleDisplay, AdvancedDisplay)
	class UImage*                                Image_1552;                                        // 0xF18(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, NoDestructor, SimpleDisplay, AdvancedDisplay)
	class UImage*                                Image_1553;                                        // 0xF20(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, Interp, NoDestructor, SimpleDisplay, AdvancedDisplay)
	class UImage*                                Image_1555;                                        // 0xF28(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, NonTransactional, NoDestructor, SimpleDisplay, AdvancedDisplay)
	class UImage*                                Image_3175;                                        // 0xF30(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, EditorOnly, AutoWeak, AdvancedDisplay, Protected)
	class UImage*                                Image_3176;                                        // 0xF38(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, EditorOnly, AutoWeak, AdvancedDisplay, Protected)
	class UImage*                                Image_3177;                                        // 0xF40(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, Interp, EditorOnly, AutoWeak, AdvancedDisplay, Protected)
	class UImage*                                Image_3178;                                        // 0xF48(0x8)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, DisableEditOnInstance, RepNotify, Interp, EditorOnly, AutoWeak, AdvancedDisplay, Protected)
	class UDataListButtonVariable_Widget_ASA_C*  INVITEINTOGROUPRANK_SLIDER;                        // 0xF50(0x8)(Edit, BlueprintReadOnly, Parm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   LeaveAllianceButton;                               // 0xF58(0x8)(BlueprintVisible, BlueprintReadOnly, Net, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   LeaveTribeButton;                                  // 0xF60(0x8)(ConstParm, BlueprintVisible, ExportObject, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* LIMITINVITES_bool;                                 // 0xF68(0x8)(BlueprintReadOnly, Net, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UScaleBox*                             LogEnabledEffect;                                  // 0xF70(0x8)(Edit, BlueprintVisible, Net, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  MAXBANISHMENTGROUPRANK_SLIDER;                     // 0xF78(0x8)(ConstParm, BlueprintVisible, Net, EditFixedSize, ZeroConstructor, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  MAXDEMOTIONGROUPRANK_SLIDER;                       // 0xF80(0x8)(Edit, ExportObject, EditFixedSize, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  MAXPROMOTIONGROUPRANK_SLIDER;                      // 0xF88(0x8)(Edit, ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  NEWSTRUCTUREACTIVATIONRANK_Slider;                 // 0xF90(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  NewStructureInventoryRankSlider;                   // 0xF98(0x8)(Parm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  NUMBEROFINVITESALLOWED_SLIDER;                     // 0xFA0(0x8)(Edit, ExportObject, BlueprintReadOnly, Net, EditFixedSize, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UProgressBar*                          OnlineMembersBar;                                  // 0xFA8(0x8)(ConstParm, BlueprintVisible, Net, EditFixedSize, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  OrderPetsRank;                                     // 0xFB0(0x8)(Edit, BlueprintReadOnly, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* PREVENTDEMOLISHINGSTRUCTURES_bool;                 // 0xFB8(0x8)(Edit, ExportObject, EditFixedSize, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* PREVENTDINOUNCLAIMING_bool;                        // 0xFC0(0x8)(Edit, BlueprintVisible, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* PREVENTSTRUCTUREBUILDINGINRANGE_bool;              // 0xFC8(0x8)(ExportObject, Net, EditFixedSize, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Bool_Widget_ASA_C* PreventWirelessCrafting_bool;                      // 0xFD0(0x8)(Edit, ExportObject, BlueprintReadOnly, Net, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   PromoteAllianceMemberButton;                       // 0xFD8(0x8)(Edit, BlueprintVisible, BlueprintReadOnly, Net, Parm, EditConst, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  RankNumberSlider;                                  // 0xFE0(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   RejectWarButton;                                   // 0xFE8(0x8)(ConstParm, BlueprintReadOnly, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   RemoveAllianceMemberButton;                        // 0xFF0(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   RemovePlayerFromTribeButton;                       // 0xFF8(0x8)(ConstParm, BlueprintVisible, Net, EditFixedSize, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   RenameAllianceButton;                              // 0x1000(0x8)(ConstParm, BlueprintVisible, ExportObject, Net, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   RenameGroupRankButton;                             // 0x1008(0x8)(ConstParm, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   RenameTribeButton;                                 // 0x1010(0x8)(Edit, ExportObject, Parm, OutParm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UTextBlock*                            RenameTribeCooldownLabel;                          // 0x1018(0x8)(Edit, ConstParm, ExportObject, BlueprintReadOnly, Net, EditFixedSize, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   ReverseLogOrderButton;                             // 0x1020(0x8)(ExportObject, BlueprintReadOnly, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, Config, DisableEditOnInstance, GlobalConfig, InstancedReference, SubobjectReference)
	class UDataListButtonVariable_Widget_ASA_C*  RidePetsRankSlider;                                // 0x1028(0x8)(BlueprintVisible, ExportObject, Net, EditFixedSize, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   SetTribeGovernmentButton;                          // 0x1030(0x8)(ExportObject, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   ShowAlliancesButton;                               // 0x1038(0x8)(Edit, BlueprintVisible, Net, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   ShowGroupRanksButton;                              // 0x1040(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UWidgetSwitcher*                       TabBgSwitcher;                                     // 0x1048(0x8)(Edit, ExportObject, ZeroConstructor, ReturnParm, DisableEditOnInstance, EditConst, GlobalConfig, SubobjectReference)
	class UImage*                                TabSplitImgPlayer;                                 // 0x1050(0x8)(Edit, ConstParm, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UImage*                                TabSplitImgRemote;                                 // 0x1058(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UTextBlock*                            TextBlock_798;                                     // 0x1060(0x8)(BlueprintVisible, ExportObject, Parm, ReturnParm, Config, DisableEditOnInstance, GlobalConfig, RepNotify, Interp, NonTransactional, EditorOnly, NoDestructor, AssetRegistrySearchable, SimpleDisplay)
	class UCustomButtonWidget*                   ToggleOnlineButton;                                // 0x1068(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, Parm, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   TribeDemoteButton;                                 // 0x1070(0x8)(Edit, ConstParm, ExportObject, EditFixedSize, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UEditableTextBox*                      TribeNameEditBox;                                  // 0x1078(0x8)(ConstParm, ExportObject, Parm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   TribePromoteButton;                                // 0x1080(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)
	class UScaleBox*                             TribesEnableEffect;                                // 0x1088(0x8)(Edit, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UCustomButtonWidget*                   TribeTransferOwnershipButton;                      // 0x1090(0x8)(BlueprintVisible, EditFixedSize, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UCanvasPanel*                          TribeWarPanel;                                     // 0x1098(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	class UScaleBox*                             WarfareEffect;                                     // 0x10A0(0x8)(Edit, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, EditConst, InstancedReference, SubobjectReference)
	class UWidgetSwitcher*                       WidgetSwitcherGovernanceAlliances;                 // 0x10A8(0x8)(Edit, BlueprintVisible, ExportObject, Net, ZeroConstructor, ReturnParm, EditConst, InstancedReference, SubobjectReference)
	class UWidgetSwitcher*                       WidgetSwitcherTribesGroups;                        // 0x10B0(0x8)(Edit, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, EditConst, InstancedReference, SubobjectReference)
	class UWidgetSwitcher*                       WidgetSwitchLogWarfare;                            // 0x10B8(0x8)(Edit, ConstParm, ExportObject, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	bool                                         IsTribeAdminForConfig;                             // 0x10C0(0x1)(Edit, EditFixedSize, Parm, OutParm, ZeroConstructor, EditConst, InstancedReference, SubobjectReference)

	static class UClass* StaticClass();
	static class UTribeManagerUI_C* GetDefaultObj();

	enum class ESlateVisibility Get_TribeWarPanel_Visibility(enum class ESlateVisibility* CallFunc_GetVisibility_ReturnValue);
	class FString CheckToBool(class UDataListButtonVariable_Widget_ASA_C** Slider, bool* Byte, bool CallFunc_EqualEqual_StrStr_ReturnValue);
	uint8 SliderToByte(class UDataListButtonVariable_Widget_ASA_C** Slider, uint8* Byte);
	struct FSlateColor SetupSwitchButtons(class UWidget* TextureEffectToHide);
	void BndEvt__TribeManagerUI_GoToGroups_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TribeManagerUI_GoToTribes_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TribeManagerUI_GoToAlliances_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TribeManagerUI_GoToGovernance_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TribeManagerUI_GoToWarfare_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TribeManagerUI_GoToTribeLog_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
	int32 BPRankGroupIndexSelected();
	int32 BPRankGroupIndexApplied();
	void Construct();
	bool ExecuteUbergraph_TribeManagerUI(int32* EntryPoint, class AShooterPlayerState* CallFunc_GetPlayerState_ReturnValue, class AShooterPlayerState* CallFunc_GetPlayerState_ReturnValue_1, class FString* CallFunc_Conv_BoolToString_ReturnValue, class FString* CallFunc_Conv_BoolToString_ReturnValue_1, class FString* CallFunc_Conv_BoolToString_ReturnValue_2, int32 CallFunc_Conv_ByteToInt_ReturnValue, int32 CallFunc_Conv_ByteToInt_ReturnValue_1, class FString* CallFunc_Conv_BoolToString_ReturnValue_3, class FString* CallFunc_Conv_BoolToString_ReturnValue_4, class FString* CallFunc_Conv_BoolToString_ReturnValue_5, class FString* CallFunc_Conv_BoolToString_ReturnValue_6, class FString* CallFunc_Conv_BoolToString_ReturnValue_7, class FString* CallFunc_Conv_BoolToString_ReturnValue_8, class FString* CallFunc_Conv_BoolToString_ReturnValue_9, class FString* CallFunc_Conv_BoolToString_ReturnValue_10, class FString* CallFunc_Conv_BoolToString_ReturnValue_11, int32 CallFunc_Conv_ByteToInt_ReturnValue_2, int32 CallFunc_Conv_ByteToInt_ReturnValue_3, int32 CallFunc_Conv_ByteToInt_ReturnValue_4, int32 CallFunc_Conv_ByteToInt_ReturnValue_5, int32 CallFunc_Conv_ByteToInt_ReturnValue_6, int32 CallFunc_Conv_ByteToInt_ReturnValue_7, int32 CallFunc_Conv_ByteToInt_ReturnValue_8, int32 CallFunc_Conv_ByteToInt_ReturnValue_9, int32 CallFunc_Conv_ByteToInt_ReturnValue_10, int32 CallFunc_Conv_ByteToInt_ReturnValue_11, int32 CallFunc_Conv_ByteToInt_ReturnValue_12, int32 CallFunc_Conv_ByteToInt_ReturnValue_13, int32* CallFunc_GetChildrenCount_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, class AShooterPlayerState* CallFunc_GetPlayerState_ReturnValue_2, int32* Temp_int_Variable, class UWidget** CallFunc_GetChildAt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, class AShooterPlayerState* CallFunc_GetPlayerState_ReturnValue_3, class FString* CallFunc_Left_ReturnValue, struct FTribeRankGroup* K2Node_MakeStruct_TribeRankGroup);
};

}


