#pragma once

// Dumped with TateDumper!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x431 (0xEA9 - 0xA78)
// WidgetBlueprintGeneratedClass CheatMenu.CheatMenu_C
class UCheatMenu_C : public UUI_DebugSpawnMenu
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xA78(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, DisableEditOnInstance, SubobjectReference)
	class UCheckBox*                             BabyCheck;                                         // 0xA80(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             BlueprintCheckBox;                                 // 0xA88(0x8)(ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UCanvasPanel*                          CharacterPresetOptions;                            // 0xA90(0x8)(ExportObject, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UCanvasPanel*                          CheatOptions;                                      // 0xA98(0x8)(ConstParm, EditFixedSize, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UEditableTextBox*                      CheatStringAddition;                               // 0xAA0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, EditFixedSize, OutParm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UButton*                               ClearFilterButton;                                 // 0xAA8(0x8)(Edit, ConstParm, BlueprintReadOnly, OutParm, ZeroConstructor, ReturnParm, Config, EditConst, SubobjectReference)
	class UButton*                               CloseButton;                                       // 0xAB0(0x8)(Edit, ConstParm, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, Config, GlobalConfig, InstancedReference, SubobjectReference)
	class UCheckBox*                             DebugTouchCheck;                                   // 0xAB8(0x8)(Edit, ConstParm, BlueprintVisible, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UCanvasPanel*                          DebugView;                                         // 0xAC0(0x8)(ConstParm, BlueprintVisible, ExportObject, Parm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	class UDataListPanel*                        DinoList;                                          // 0xAC8(0x8)(Edit, ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UCanvasPanel*                          DinoOptions;                                       // 0xAD0(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Net, Config, EditConst, SubobjectReference)
	class UEditableTextBox*                      DinoSpawnLevelBox;                                 // 0xAD8(0x8)(ConstParm, ExportObject, EditFixedSize, Parm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCanvasPanel*                          EggOptions;                                        // 0xAE0(0x8)(Edit, ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, ReturnParm, Config, EditConst, SubobjectReference)
	class UCheckBox*                             EngramCheckBox;                                    // 0xAE8(0x8)(Edit, ExportObject, Net, EditFixedSize, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             FemaleCheck;                                       // 0xAF0(0x8)(BlueprintVisible, ExportObject, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             FertilizedCheckBox;                                // 0xAF8(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, OutParm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCanvasPanel*                          FilterPanel;                                       // 0xB00(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, Parm, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UImage*                                Image;                                             // 0xB08(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Config, DisableEditOnInstance)
	class UImage*                                Image_4;                                           // 0xB10(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Config, DisableEditOnInstance, RepNotify, NonTransactional)
	class UImage*                                Image_48;                                          // 0xB18(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Config, DisableEditOnInstance, RepNotify, NoDestructor)
	class UImage*                                Image_97;                                          // 0xB20(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Config, DisableEditOnInstance, Interp, AutoWeak)
	class UCheckBox*                             IncludeItemsCheck;                                 // 0xB28(0x8)(Edit, EditFixedSize, OutParm, ZeroConstructor, Transient, EditConst, SubobjectReference)
	class UCanvasPanel*                          ItemOptions;                                       // 0xB30(0x8)(Edit, BlueprintVisible, EditFixedSize, Parm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UCheckBox*                             MaleCheck;                                         // 0xB38(0x8)(ConstParm, ExportObject, BlueprintReadOnly, OutParm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	class UEditableTextBox*                      NamesFilterInputField;                             // 0xB40(0x8)(Edit, ConstParm, ExportObject, Net, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	class UEditableTextBox*                      NumberEggsToSpawn;                                 // 0xB48(0x8)(Net, EditFixedSize, Parm, OutParm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UEditableTextBox*                      NumToSpawnTextBox;                                 // 0xB50(0x8)(Edit, ConstParm, ExportObject, BlueprintReadOnly, Parm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UEditableTextBox*                      QualityToSpawnTextBox;                             // 0xB58(0x8)(Edit, BlueprintVisible, Net, Parm, ReturnParm, Transient, EditConst, SubobjectReference)
	class UTextBlock*                            ReferenceText;                                     // 0xB60(0x8)(Edit, ConstParm, ExportObject, Config, EditConst, SubobjectReference)
	class UCheckBox*                             SaddleCheck;                                       // 0xB68(0x8)(BlueprintVisible, ExportObject, EditFixedSize, OutParm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	class UCheckBox*                             TameCheck;                                         // 0xB70(0x8)(ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, OutParm, ZeroConstructor, ReturnParm, Transient, EditConst, SubobjectReference)
	class UButton*                               ToDinosButton;                                     // 0xB78(0x8)(ConstParm, ExportObject, BlueprintReadOnly, Net, OutParm, ZeroConstructor, Config, EditConst, SubobjectReference)
	int32                                        ScreenTracker;                                     // 0xB80(0x4)(BlueprintVisible, EditFixedSize, Parm, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	uint8                                        Pad_314B[0x4];                                     // Fixing Size After Last Property  > TateDumper <
	TArray<class FText>                          FolderNames;                                       // 0xB88(0x10)(Edit, BlueprintVisible, ExportObject, Net, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class UUI_DebugSpawnMenuEntry*>       DebugEntries;                                      // 0xB98(0x10)(Edit, ConstParm, BlueprintReadOnly, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        DinoNames;                                         // 0xBA8(0x10)(ConstParm, BlueprintReadOnly, Net, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        DinoEggNames;                                      // 0xBB8(0x10)(BlueprintVisible, ExportObject, Net, EditFixedSize, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        CheatNames;                                        // 0xBC8(0x10)(EditFixedSize, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<class FString>                        CheatStrings;                                      // 0xBD8(0x10)(BlueprintVisible, Net, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        CharacterPresetStrings;                            // 0xBE8(0x10)(BlueprintReadOnly, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<struct FCheatMenuCharacterLevelPreset> CharacterPresetLevel;                              // 0xBF8(0x10)(BlueprintVisible, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        ScorchedEarthDinoNames;                            // 0xC08(0x10)(BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<enum class ECheatMenuOptionTypes>     OptionTypes;                                       // 0xC18(0x10)(Edit, ConstParm, ExportObject, Net, OutParm, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ScorchedEarthEggNames;                             // 0xC28(0x10)(ConstParm, BlueprintReadOnly, EditFixedSize, Parm, ZeroConstructor, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             IslandMapJumpInfos;                                // 0xC38(0x10)(Edit, BlueprintVisible, Net, EditFixedSize, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        MapOpenCheats;                                     // 0xC48(0x10)(Edit, ExportObject, Net, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        OpenMapNames;                                      // 0xC58(0x10)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             SE_MapJumpInfos;                                   // 0xC68(0x10)(Edit, ConstParm, BlueprintVisible, ExportObject, EditFixedSize, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ReferenceTexts;                                    // 0xC78(0x10)(Edit, ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             CenterMapJumpInfos;                                // 0xC88(0x10)(BlueprintReadOnly, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             AberrationMapJumpInfos;                            // 0xC98(0x10)(ConstParm, Parm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             RagnarokMapJumpInfos;                              // 0xCA8(0x10)(ConstParm, BlueprintReadOnly, Net, OutParm, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             ExtinctionMapJumpInfos;                            // 0xCB8(0x10)(ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             ValgueroMapJumpInfos;                              // 0xCC8(0x10)(BlueprintVisible, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             CrystalIslesMapJumpInfos;                          // 0xCD8(0x10)(ConstParm, Net, EditFixedSize, OutParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             GenesisMapJumpInfos;                               // 0xCE8(0x10)(ConstParm, BlueprintVisible, Net, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             Gen2MapJumpInfos;                                  // 0xCF8(0x10)(ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<struct FCheatMapJumpInfo>             LostIslandMapJumpInfos;                            // 0xD08(0x10)(BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<bool>                                 CheatConfirmation;                                 // 0xD18(0x10)(Edit, ExportObject, BlueprintReadOnly, Net, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        IslandBossStrings;                                 // 0xD28(0x10)(Edit, ConstParm, ExportObject, Net, Parm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        IslandBossCheats;                                  // 0xD38(0x10)(BlueprintReadOnly, Parm, OutParm, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        SEBossCheats;                                      // 0xD48(0x10)(Edit, ConstParm, OutParm, ZeroConstructor, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        SEBossStrings;                                     // 0xD58(0x10)(Edit, ExportObject, BlueprintReadOnly, Net, Parm, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        AberrationBossStrings;                             // 0xD68(0x10)(ConstParm, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, Config, EditConst, SubobjectReference)
	TArray<class FString>                        AberrationBossCheats;                              // 0xD78(0x10)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtinctionBossCheats;                              // 0xD88(0x10)(Edit, BlueprintVisible, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtinctionBossStrings;                             // 0xD98(0x10)(Edit, ConstParm, ExportObject, Net, EditFixedSize, Parm, Config, EditConst, SubobjectReference)
	TArray<class FString>                        CenterBossCheats;                                  // 0xDA8(0x10)(ExportObject, BlueprintReadOnly, EditFixedSize, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        CenterBossStrings;                                 // 0xDB8(0x10)(ConstParm, ExportObject, Net, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        RagnarokBossCheats;                                // 0xDC8(0x10)(ConstParm, ExportObject, BlueprintReadOnly, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        RagnarokBossStrings;                               // 0xDD8(0x10)(Edit, ConstParm, ExportObject, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ValgueroBossCheats;                                // 0xDE8(0x10)(ConstParm, BlueprintReadOnly, Net, EditFixedSize, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ValgueroBossStrings;                               // 0xDF8(0x10)(Edit, BlueprintReadOnly, OutParm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        AberrationUniqueDinoNames;                         // 0xE08(0x10)(Edit, BlueprintReadOnly, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        AberrantDinoNames;                                 // 0xE18(0x10)(BlueprintVisible, BlueprintReadOnly, Parm, ReturnParm, Config, EditConst, SubobjectReference)
	TArray<class FString>                        Community_Dino_Names;                              // 0xE28(0x10)(Edit, EditFixedSize, Parm, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtinctionDinoNames;                               // 0xE38(0x10)(ExportObject, BlueprintReadOnly, EditFixedSize, ZeroConstructor, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtinctionCorruptDinoNames;                        // 0xE48(0x10)(BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<bool>                                 OptionsIsEngram;                                   // 0xE58(0x10)(Edit, ConstParm, ExportObject, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<int32>                                OptionsQuantity;                                   // 0xE68(0x10)(Edit, ConstParm, BlueprintReadOnly, Net, EditFixedSize, Parm, ReturnParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)
	TArray<class FString>                        ExtionctionEggNames;                               // 0xE78(0x10)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, ReturnParm, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	TArray<class FString>                        EventDinoNames;                                    // 0xE88(0x10)(Edit, ConstParm, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Transient, EditConst, SubobjectReference)
	class FString                                FilterName;                                        // 0xE98(0x10)(BlueprintVisible, ExportObject, EditFixedSize, Parm, Config, EditConst, SubobjectReference)
	bool                                         IgnoreFilterChange;                                // 0xEA8(0x1)(BlueprintVisible, Net, EditFixedSize, Parm, OutParm, DisableEditOnTemplate, Config, EditConst, SubobjectReference)

	static class UClass* StaticClass();
	static class UCheatMenu_C* GetDefaultObj();

	bool BPEscapeClosed(bool* ReturnValue, class AShooterHUD** CallFunc_GetShooterHUD_ReturnValue, bool* CallFunc_CloseSpawnMenu_ReturnValue);
	void ClearFilter(bool* ShouldRefresh);
	class FString GetBossSpawnArray(const TArray<class FString>& BossNames, const TArray<class FString>& BossCheats, bool K2Node_SwitchString_CmpSuccess);
	void CloseMenu(class AShooterHUD** CallFunc_GetShooterHUD_ReturnValue, bool* CallFunc_CloseSpawnMenu_ReturnValue);
	bool GetMapOpenListsForEntry(bool Success);
	class APlayerController* CreateMapOpenButton(class FString* Name, class FName MapName, class UUI_DebugSpawnMenuEntry** CreatedWidget, class FText* CallFunc_Conv_StringToText_ReturnValue, class UCheatMenuMapOpenButton_C* CallFunc_Create_ReturnValue);
	class UUI_DebugSpawnMenuEntry* CreateMapOpenEntry(class FString* Name, TArray<class FString>* Array, class FName* CallFunc_Conv_StringToName_ReturnValue, int32* CallFunc_Array_Add_ReturnValue);
	int32 GetMapJumpArray(bool CallFunc_LessEqual_IntInt_ReturnValue, int32* CallFunc_Add_IntInt_ReturnValue, TArray<struct FCheatMapJumpInfo>* CallFunc_GetMapJumpListForEntry_MapJumps, int32* CallFunc_Array_Add_ReturnValue);
	class APlayerController* CreateMapJumpButton(class UUI_DebugSpawnMenuEntry** CreatedWidget, class FText* CallFunc_Conv_StringToText_ReturnValue, class UCheatMapJumpButton_C* CallFunc_Create_ReturnValue);
	struct FCheatMapJumpInfo CreateMapJumpEntry(class UUI_DebugSpawnMenuEntry** CallFunc_CreateMapJumpButton_CreatedWidget, int32* CallFunc_Array_Add_ReturnValue);
	class FString GetMapJumpListForEntry(bool Success, bool K2Node_SwitchString_CmpSuccess);
	bool AddAllEntriesButtonForItems(const TArray<TSoftClassPtr<class UPrimalItem>>& Items);
	void CreateButtonFromAllEntries(const TArray<TSoftClassPtr<class UPrimalItem>>& Items, class UCheatMenuItemAllButton_C** ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UCheatMenuItemAllButton_C* CallFunc_Create_ReturnValue);
	void HideAllOptions();
	bool SetupOptionsBarForFolder(bool* Temp_bool_Variable, enum class ESlateVisibility* Temp_byte_Variable, enum class ESlateVisibility* Temp_byte_Variable_1, bool* Temp_bool_Variable_1, enum class ESlateVisibility* Temp_byte_Variable_2, enum class ESlateVisibility* Temp_byte_Variable_3, bool* Temp_bool_Variable_2, enum class ESlateVisibility* Temp_byte_Variable_4, enum class ESlateVisibility* Temp_byte_Variable_5, bool* Temp_bool_Variable_3, enum class ESlateVisibility* Temp_byte_Variable_6, enum class ESlateVisibility* Temp_byte_Variable_7, bool* Temp_bool_Variable_4, enum class ESlateVisibility* Temp_byte_Variable_8, enum class ESlateVisibility* Temp_byte_Variable_9, enum class ESlateVisibility* K2Node_Select_Default, enum class ESlateVisibility* K2Node_Select_Default_1, enum class ESlateVisibility* K2Node_Select_Default_2, enum class ESlateVisibility* K2Node_Select_Default_3, enum class ESlateVisibility* K2Node_Select_Default_4);
	bool GetCharacterPresetsForEntry(const TArray<struct FCheatMenuCharacterPresetItems>& CharacterPresetItem, bool Success);
	bool GetCheatListsForEntry(const TArray<bool>& RequireConfirm, bool Success, const TArray<class FString>& CallFunc_GetBossSpawnArray_BossNames, TArray<class FString>* CallFunc_GetBossSpawnArray_BossCheats);
	bool GetEggListsForEntry(bool Success);
	bool GetDinoListsForEntry(bool Success);
	struct FCheatMenuCharacterLevelPreset CreateCharacterPresetEntry(TArray<struct FCheatMenuCharacterLevelPreset>* LevelLists, class FText* CallFunc_Conv_StringToText_ReturnValue, class UUI_DebugSpawnMenuEntry* CallFunc_CreateButtonFromCharacterPresets_CreatedWidget, int32* CallFunc_Array_Add_ReturnValue);
	class UUI_DebugSpawnMenuEntry* CreateCheatEntry(class FString* Name, TArray<class FString>* Array, bool* Temp_bool_Variable, bool CallFunc_Array_IsValidIndex_ReturnValue, bool* Temp_bool_Variable_1, bool* K2Node_Select_Default, int32* CallFunc_Array_Add_ReturnValue);
	class UUI_DebugSpawnMenuEntry* CreateEggEntry(class FString* Name, const TArray<TSoftClassPtr<class UPrimalItem>>& UnFertEggs, TArray<TSoftClassPtr<class UPrimalItem>>* FertEggs, bool CallFunc_BooleanOR_ReturnValue, bool* Temp_bool_Variable, class FString* K2Node_Select_Default, class FString* CallFunc_Concat_StrStr_ReturnValue, int32* CallFunc_Array_Add_ReturnValue);
	bool CreateDinoEntry(const TArray<TSoftClassPtr<class APrimalDinoCharacter>>& DinoBPList, TArray<TSoftClassPtr<class UPrimalItem>>* DinoSaddleList, int32* CallFunc_Array_Add_ReturnValue);
	bool SetupOptionBar(class FText* CallFunc_Conv_IntToText_ReturnValue);
	bool CreateButtonFromCharacterPresets(class FText* Name, const struct FCheatMenuCharacterLevelPreset& Levels, const struct FCheatMenuCharacterPresetItems& Items, class UUI_DebugSpawnMenuEntry** CreatedWidget, class UCheatMenuCharacterPresetsButton_C* CallFunc_Create_ReturnValue);
	class APlayerController* CreateFolderButtons(class FText* Name, int32 ScreenNumber, class UTexture2D** Image, class UUI_DebugSpawnMenuEntry** OutWidget, class UCheatMenuFolderButton_C* CallFunc_Create_ReturnValue);
	class APlayerController* CreateCheatButtonFromBlueprintID(class FString* Name, bool RequireConfirm, bool Allow_Additional_String, class UUI_DebugSpawnMenuEntry** CreatedWidget, class FText* CallFunc_Conv_StringToText_ReturnValue, class UCheatMenuCheatButton_C* CallFunc_Create_ReturnValue);
	bool CreateEggItemButtonFromBlueprintIDs(class FString* Name, TSoftClassPtr<class UPrimalItem> FertilizedEgg, class UUI_DebugSpawnMenuEntry** CreatedWidget, bool* Temp_bool_Variable, class FText* CallFunc_Conv_StringToText_ReturnValue, bool* CallFunc_IsValidClass_ReturnValue, class UClass** K2Node_Select_Default, class UClass* K2Node_ClassDynamicCast_AsPrimal_Item, bool* K2Node_ClassDynamicCast_bSuccess, class UCheatMenuEggButton_C* CallFunc_Create_ReturnValue);
	class APlayerController* CreateItemButtonFromBlueprintID(TSoftClassPtr<class UPrimalItem>* Blueprint, class UUI_DebugSpawnMenuEntry** CreatedWidget, class UClass* K2Node_ClassDynamicCast_AsPrimal_Item, bool* K2Node_ClassDynamicCast_bSuccess, class UCheatMenuItemButton_C* CallFunc_Create_ReturnValue);
	class APlayerController* CreateItemButtonAndSetText(const class FString& ItemName, const class FString& ItemSpawnString, class UCheatMenuButton_C* CreatedButton, class FText* CallFunc_Conv_StringToText_ReturnValue, class UCheatMenuItemButton_C* CallFunc_Create_ReturnValue);
	class APlayerController* CreateDinoButtonAndSetText(class UCheatMenuButton_C* CreatedButton, class FText* CallFunc_Conv_StringToText_ReturnValue, class UCheatMenuButton_C* CallFunc_Create_ReturnValue);
	void Construct();
	void BndEvt__CloseButton_K2Node_ComponentBoundEvent_126_OnButtonClickedEvent__DelegateSignature();
	enum class ETextCommit BndEvt__EditableTextBox_139_K2Node_ComponentBoundEvent_360_OnEditableTextBoxCommittedEvent__DelegateSignature();
	enum class ETextCommit BndEvt__DinoSpawnLevelBox_K2Node_ComponentBoundEvent_41_OnEditableTextBoxCommittedEvent__DelegateSignature();
	void BndEvt__ToDinosButton_K2Node_ComponentBoundEvent_319_OnButtonPressedEvent__DelegateSignature();
	enum class ETextCommit BndEvt__NumberEggsToSpawn_K2Node_ComponentBoundEvent_232_OnEditableTextBoxCommittedEvent__DelegateSignature();
	int32 Screen_Changed();
	void OnHome();
	void BndEvt__BlueprintCheckBox_K2Node_ComponentBoundEvent_19_OnCheckBoxComponentStateChanged__DelegateSignature(bool* bIsChecked);
	void BndEvt__SpawnMenu_TameCheck_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature(bool* bIsChecked);
	class FText BndEvt__CheatMenu_NamesFilterInputField_K2Node_ComponentBoundEvent_1_OnEditableTextBoxChangedEvent__DelegateSignature();
	void BndEvt__CheatMenu_Button_131_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	bool ExecuteUbergraph_CheatMenu(int32* EntryPoint, bool* Temp_bool_Variable, bool CallFunc_GreaterEqual_IntInt_ReturnValue, enum class ECheckBoxState* Temp_byte_Variable, enum class ECheckBoxState* Temp_byte_Variable_1, bool* Temp_bool_Variable_1, enum class ESlateVisibility* Temp_byte_Variable_2, enum class ESlateVisibility* Temp_byte_Variable_3, int32* CallFunc_Add_IntInt_ReturnValue, int32* CallFunc_Add_IntInt_ReturnValue_1, int32* CallFunc_Add_IntInt_ReturnValue_2, int32* CallFunc_Add_IntInt_ReturnValue_3, int32* CallFunc_Add_IntInt_ReturnValue_4, enum class ETextCommit* K2Node_ComponentBoundEvent_CommitMethod_2, class FString* CallFunc_Conv_TextToString_ReturnValue, enum class ETextCommit* K2Node_ComponentBoundEvent_CommitMethod_1, class FString* CallFunc_Conv_TextToString_ReturnValue_1, class FText* CallFunc_Conv_IntToText_ReturnValue, class FText* CallFunc_Conv_IntToText_ReturnValue_1, enum class ETextCommit* K2Node_ComponentBoundEvent_CommitMethod, class FString* CallFunc_Conv_TextToString_ReturnValue_2, class FText* CallFunc_Conv_IntToText_ReturnValue_2, bool CallFunc_EqualEqual_StrStr_ReturnValue, int32* K2Node_CustomEvent_ToScreen, enum class ECheckBoxState* K2Node_Select_Default, enum class ESlateVisibility* K2Node_Select_Default_1, TArray<TSoftClassPtr<class UPrimalItem>>* CallFunc_GetDinoListsForEntry_Saddles, const TArray<TSoftClassPtr<class UPrimalItem>>& CallFunc_GetEggListsForEntry_DinoEggBlueprintIDs, const TArray<TSoftClassPtr<class UPrimalItem>>& CallFunc_GetEggListsForEntry_DinoFertEggBlueprintIDs, TArray<class FString>* CallFunc_GetCheatListsForEntry_CheatStrings, const TArray<bool>& CallFunc_GetCheatListsForEntry_RequireConfirm, bool* CallFunc_GetCheatListsForEntry_AllowAdditionalString, TArray<struct FCheatMenuCharacterLevelPreset>* CallFunc_GetCharacterPresetsForEntry_CharacterPresetLevel, const TArray<struct FCheatMenuCharacterPresetItems>& CallFunc_GetCharacterPresetsForEntry_CharacterPresetItem, TArray<struct FCheatMapJumpInfo>* CallFunc_GetMapJumpListForEntry_MapJumps, TArray<class FString>* CallFunc_GetMapJumpArray_EmptyStringArray, const TArray<class FString>& CallFunc_GetMapOpenListsForEntry_CheatStrings, int32* CallFunc_Array_Add_ReturnValue, class FText* CallFunc_Conv_StringToText_ReturnValue, const TArray<class FString>& CallFunc_GetBossSpawnArray_BossNames, TArray<class FString>* CallFunc_GetBossSpawnArray_BossCheats, TArray<TSoftClassPtr<class UPrimalItem>>* K2Node_Select_Default_2, class FString* CallFunc_Conv_TextToString_ReturnValue_3, int32* CallFunc_Array_Add_ReturnValue_1, bool CallFunc_EqualEqual_StrStr_ReturnValue_1, TArray<class FString>* K2Node_Select_Default_3, bool CallFunc_EqualEqual_StrStr_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2);
};

}


